// Mocks generated by Mockito 5.4.6 from annotations
// in greenhive_app/test/features/admin/presentation/admin_users_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:cloud_firestore/cloud_firestore.dart' as _i5;
import 'package:greenhive_app/core/logging/app_logger.dart' as _i6;
import 'package:greenhive_app/features/admin/data/models/admin_user.dart'
    as _i4;
import 'package:greenhive_app/features/admin/services/admin_user_service.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AdminUserService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdminUserService extends _i1.Mock implements _i2.AdminUserService {
  MockAdminUserService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.AdminUser>> getUsers({
    String? searchQuery,
    String? roleFilter,
    bool? isSuspended,
    bool? isExpert,
    int? limit = 50,
    _i5.DocumentSnapshot<Object?>? startAfter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUsers, [], {
              #searchQuery: searchQuery,
              #roleFilter: roleFilter,
              #isSuspended: isSuspended,
              #isExpert: isExpert,
              #limit: limit,
              #startAfter: startAfter,
            }),
            returnValue: _i3.Future<List<_i4.AdminUser>>.value(
              <_i4.AdminUser>[],
            ),
          )
          as _i3.Future<List<_i4.AdminUser>>);

  @override
  _i3.Future<List<_i4.AdminUser>> searchUsers(
    String? query, {
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchUsers, [query], {#limit: limit}),
            returnValue: _i3.Future<List<_i4.AdminUser>>.value(
              <_i4.AdminUser>[],
            ),
          )
          as _i3.Future<List<_i4.AdminUser>>);

  @override
  _i3.Future<_i4.AdminUser?> getUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUser, [userId]),
            returnValue: _i3.Future<_i4.AdminUser?>.value(),
          )
          as _i3.Future<_i4.AdminUser?>);

  @override
  _i3.Future<bool> suspendUser(String? userId, String? reason) =>
      (super.noSuchMethod(
            Invocation.method(#suspendUser, [userId, reason]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> unsuspendUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#unsuspendUser, [userId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> updateRoles(String? userId, List<String>? roles) =>
      (super.noSuchMethod(
            Invocation.method(#updateRoles, [userId, roles]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> addRole(String? userId, String? role) =>
      (super.noSuchMethod(
            Invocation.method(#addRole, [userId, role]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> removeRole(String? userId, String? role) =>
      (super.noSuchMethod(
            Invocation.method(#removeRole, [userId, role]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<Map<String, int>> getStats() =>
      (super.noSuchMethod(
            Invocation.method(#getStats, []),
            returnValue: _i3.Future<Map<String, int>>.value(<String, int>{}),
          )
          as _i3.Future<Map<String, int>>);
}

/// A class which mocks [AppLogger].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppLogger extends _i1.Mock implements _i6.AppLogger {
  MockAppLogger() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void verbose(String? message, {String? tag, Map<String, dynamic>? data}) =>
      super.noSuchMethod(
        Invocation.method(#verbose, [message], {#tag: tag, #data: data}),
        returnValueForMissingStub: null,
      );

  @override
  void debug(String? message, {String? tag, Map<String, dynamic>? data}) =>
      super.noSuchMethod(
        Invocation.method(#debug, [message], {#tag: tag, #data: data}),
        returnValueForMissingStub: null,
      );

  @override
  void info(String? message, {String? tag, Map<String, dynamic>? data}) =>
      super.noSuchMethod(
        Invocation.method(#info, [message], {#tag: tag, #data: data}),
        returnValueForMissingStub: null,
      );

  @override
  void warning(String? message, {String? tag, Map<String, dynamic>? data}) =>
      super.noSuchMethod(
        Invocation.method(#warning, [message], {#tag: tag, #data: data}),
        returnValueForMissingStub: null,
      );

  @override
  void error(
    String? message, {
    String? tag,
    dynamic error,
    StackTrace? stackTrace,
    Map<String, dynamic>? data,
  }) => super.noSuchMethod(
    Invocation.method(
      #error,
      [message],
      {#tag: tag, #error: error, #stackTrace: stackTrace, #data: data},
    ),
    returnValueForMissingStub: null,
  );
}
