// Mocks generated by Mockito 5.4.6 from annotations
// in securityexperts_app/test/features/admin/presentation/admin_dashboard_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cloud_firestore/cloud_firestore.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:securityexperts_app/core/logging/app_logger.dart' as _i8;
import 'package:securityexperts_app/features/admin/data/models/internal_note.dart'
    as _i7;
import 'package:securityexperts_app/features/admin/data/models/ticket_stats.dart'
    as _i2;
import 'package:securityexperts_app/features/admin/services/admin_ticket_service.dart'
    as _i3;
import 'package:securityexperts_app/features/support/data/models/models.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTicketStats_0 extends _i1.SmartFake implements _i2.TicketStats {
  _FakeTicketStats_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AdminTicketService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdminTicketService extends _i1.Mock
    implements _i3.AdminTicketService {
  MockAdminTicketService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.SupportTicket>> getAllTickets({
    _i5.TicketStatus? statusFilter,
    _i5.TicketPriority? priorityFilter,
    _i5.TicketCategory? categoryFilter,
    String? assignedTo,
    bool? unassignedOnly = false,
    int? limit = 50,
    _i6.DocumentSnapshot<Object?>? startAfter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAllTickets, [], {
              #statusFilter: statusFilter,
              #priorityFilter: priorityFilter,
              #categoryFilter: categoryFilter,
              #assignedTo: assignedTo,
              #unassignedOnly: unassignedOnly,
              #limit: limit,
              #startAfter: startAfter,
            }),
            returnValue: _i4.Future<List<_i5.SupportTicket>>.value(
              <_i5.SupportTicket>[],
            ),
          )
          as _i4.Future<List<_i5.SupportTicket>>);

  @override
  _i4.Stream<List<_i5.SupportTicket>> watchAllTickets({
    _i5.TicketStatus? statusFilter,
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watchAllTickets, [], {
              #statusFilter: statusFilter,
              #limit: limit,
            }),
            returnValue: _i4.Stream<List<_i5.SupportTicket>>.empty(),
          )
          as _i4.Stream<List<_i5.SupportTicket>>);

  @override
  _i4.Future<_i5.SupportTicket?> getTicket(String? ticketId) =>
      (super.noSuchMethod(
            Invocation.method(#getTicket, [ticketId]),
            returnValue: _i4.Future<_i5.SupportTicket?>.value(),
          )
          as _i4.Future<_i5.SupportTicket?>);

  @override
  _i4.Stream<_i5.SupportTicket?> watchTicket(String? ticketId) =>
      (super.noSuchMethod(
            Invocation.method(#watchTicket, [ticketId]),
            returnValue: _i4.Stream<_i5.SupportTicket?>.empty(),
          )
          as _i4.Stream<_i5.SupportTicket?>);

  @override
  _i4.Future<bool> updateStatus(
    String? ticketId,
    _i5.TicketStatus? newStatus,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateStatus, [ticketId, newStatus]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> updatePriority(
    String? ticketId,
    _i5.TicketPriority? newPriority,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePriority, [ticketId, newPriority]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> assignTicket(String? ticketId, String? agentId) =>
      (super.noSuchMethod(
            Invocation.method(#assignTicket, [ticketId, agentId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> updateResolution(
    String? ticketId, {
    required String? resolution,
    required _i5.ResolutionType? resolutionType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateResolution,
              [ticketId],
              {#resolution: resolution, #resolutionType: resolutionType},
            ),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<List<_i7.InternalNote>> getInternalNotes(String? ticketId) =>
      (super.noSuchMethod(
            Invocation.method(#getInternalNotes, [ticketId]),
            returnValue: _i4.Future<List<_i7.InternalNote>>.value(
              <_i7.InternalNote>[],
            ),
          )
          as _i4.Future<List<_i7.InternalNote>>);

  @override
  _i4.Stream<List<_i7.InternalNote>> watchInternalNotes(String? ticketId) =>
      (super.noSuchMethod(
            Invocation.method(#watchInternalNotes, [ticketId]),
            returnValue: _i4.Stream<List<_i7.InternalNote>>.empty(),
          )
          as _i4.Stream<List<_i7.InternalNote>>);

  @override
  _i4.Future<_i7.InternalNote?> addInternalNote({
    required String? ticketId,
    required String? authorId,
    required String? authorName,
    required String? content,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addInternalNote, [], {
              #ticketId: ticketId,
              #authorId: authorId,
              #authorName: authorName,
              #content: content,
            }),
            returnValue: _i4.Future<_i7.InternalNote?>.value(),
          )
          as _i4.Future<_i7.InternalNote?>);

  @override
  _i4.Future<_i2.TicketStats> getTicketStats() =>
      (super.noSuchMethod(
            Invocation.method(#getTicketStats, []),
            returnValue: _i4.Future<_i2.TicketStats>.value(
              _FakeTicketStats_0(this, Invocation.method(#getTicketStats, [])),
            ),
          )
          as _i4.Future<_i2.TicketStats>);

  @override
  _i4.Future<bool> sendAdminReply({
    required String? ticketId,
    required String? senderId,
    required String? senderName,
    required String? content,
    List<_i5.TicketAttachment>? attachments = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendAdminReply, [], {
              #ticketId: ticketId,
              #senderId: senderId,
              #senderName: senderName,
              #content: content,
              #attachments: attachments,
            }),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}

/// A class which mocks [AppLogger].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppLogger extends _i1.Mock implements _i8.AppLogger {
  MockAppLogger() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void verbose(String? message, {String? tag, Map<String, dynamic>? data}) =>
      super.noSuchMethod(
        Invocation.method(#verbose, [message], {#tag: tag, #data: data}),
        returnValueForMissingStub: null,
      );

  @override
  void debug(String? message, {String? tag, Map<String, dynamic>? data}) =>
      super.noSuchMethod(
        Invocation.method(#debug, [message], {#tag: tag, #data: data}),
        returnValueForMissingStub: null,
      );

  @override
  void info(String? message, {String? tag, Map<String, dynamic>? data}) =>
      super.noSuchMethod(
        Invocation.method(#info, [message], {#tag: tag, #data: data}),
        returnValueForMissingStub: null,
      );

  @override
  void warning(String? message, {String? tag, Map<String, dynamic>? data}) =>
      super.noSuchMethod(
        Invocation.method(#warning, [message], {#tag: tag, #data: data}),
        returnValueForMissingStub: null,
      );

  @override
  void error(
    String? message, {
    String? tag,
    dynamic error,
    StackTrace? stackTrace,
    Map<String, dynamic>? data,
  }) => super.noSuchMethod(
    Invocation.method(
      #error,
      [message],
      {#tag: tag, #error: error, #stackTrace: stackTrace, #data: data},
    ),
    returnValueForMissingStub: null,
  );
}
