include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/deprecated/**
  errors:
    # Suppress file_picker plugin metadata warning (known issue with maintainers)
    duplicate_ignore: ignore
    invalid_use_of_internal_member: ignore

linter:
  rules:
    # === Code quality (KEEP ENABLED) ===
    always_declare_return_types: true
    avoid_empty_else: true
    avoid_print: true
    avoid_relative_lib_imports: true
    avoid_returning_null_for_void: true
    avoid_types_as_parameter_names: true
    avoid_unnecessary_containers: true
    cancel_subscriptions: true
    close_sinks: true
    prefer_final_fields: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    sort_child_properties_last: true
    unnecessary_brace_in_string_interps: true
    unnecessary_const: true
    unnecessary_new: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_parenthesis: true
    unnecessary_string_interpolations: true
    use_key_in_widget_constructors: true

    # === Style preferences (DISABLED - too noisy, minimal benefit) ===
    prefer_const_constructors: false
    prefer_const_declarations: false
    prefer_final_locals: false
    prefer_single_quotes: false
    avoid_void_async: false

# ============================================================================
# UI STANDARDS ENFORCEMENT
# ============================================================================
# The following patterns should be avoided to maintain UI consistency:
#
# ❌ Colors.xxx        → Use AppColors.xxx
# ❌ Color(0x...)      → Add to AppColors and use constant
# ❌ fontSize: N       → Use AppTypography.xxx
# ❌ EdgeInsets.all(N) → Use EdgeInsets.all(AppSpacing.spacingN)
# ❌ BorderRadius.circular(N) → Use BorderRadius.circular(AppBorders.radiusN)
#
# Run ./scripts/check_ui_standards.sh to check for violations
# ============================================================================
