// Mocks generated by Mockito 5.4.6 from annotations
// in securityexperts_app/test/features/calling/presentation/call_history_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:cloud_firestore/cloud_firestore.dart' as _i4;
import 'package:securityexperts_app/features/calling/domain/repositories/call_history_repository.dart'
    as _i2;
import 'package:securityexperts_app/features/calling/services/call_logger.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [CallHistoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCallHistoryRepository extends _i1.Mock
    implements _i2.CallHistoryRepository {
  MockCallHistoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i4.QuerySnapshot<Object?>> getCallHistoryStream(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getCallHistoryStream, [userId]),
            returnValue: _i3.Stream<_i4.QuerySnapshot<Object?>>.empty(),
          )
          as _i3.Stream<_i4.QuerySnapshot<Object?>>);

  @override
  _i3.Future<bool> deleteCallHistoryEntry(
    String? userId,
    String? callHistoryId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCallHistoryEntry, [userId, callHistoryId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<int> deleteCallHistoryEntries(
    String? userId,
    List<String>? callHistoryIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCallHistoryEntries, [
              userId,
              callHistoryIds,
            ]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<bool> clearAllCallHistory(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#clearAllCallHistory, [userId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<int> getCallHistoryCount(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getCallHistoryCount, [userId]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);
}

/// A class which mocks [CallLogger].
///
/// See the documentation for Mockito's code generation for more information.
class MockCallLogger extends _i1.Mock implements _i5.CallLogger {
  MockCallLogger() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void info(String? message, [Map<String, dynamic>? data]) =>
      super.noSuchMethod(
        Invocation.method(#info, [message, data]),
        returnValueForMissingStub: null,
      );

  @override
  void warning(String? message, [Map<String, dynamic>? data]) =>
      super.noSuchMethod(
        Invocation.method(#warning, [message, data]),
        returnValueForMissingStub: null,
      );

  @override
  void error(String? message, dynamic error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(
        Invocation.method(#error, [message, error, stackTrace]),
        returnValueForMissingStub: null,
      );

  @override
  void debug(String? message, [Map<String, dynamic>? data]) =>
      super.noSuchMethod(
        Invocation.method(#debug, [message, data]),
        returnValueForMissingStub: null,
      );
}
