// Mocks generated by Mockito 5.4.6 from annotations
// in greenhive_app/test/features/support/presentation/ticket_list_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:securityexperts_app/features/support/data/models/models.dart' as _i4;
import 'package:securityexperts_app/features/support/services/support_analytics.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [SupportAnalytics].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupportAnalytics extends _i1.Mock implements _i2.SupportAnalytics {
  MockSupportAnalytics() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> trackHubOpened() =>
      (super.noSuchMethod(
            Invocation.method(#trackHubOpened, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> trackTicketStarted({required _i4.TicketType? type}) =>
      (super.noSuchMethod(
            Invocation.method(#trackTicketStarted, [], {#type: type}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> trackTicketSubmitted({
    required String? ticketId,
    required _i4.TicketType? type,
    required _i4.TicketCategory? category,
    required _i4.TicketPriority? priority,
    required int? attachmentCount,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackTicketSubmitted, [], {
              #ticketId: ticketId,
              #type: type,
              #category: category,
              #priority: priority,
              #attachmentCount: attachmentCount,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> trackTicketViewed({
    required String? ticketId,
    required _i4.TicketStatus? status,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackTicketViewed, [], {
              #ticketId: ticketId,
              #status: status,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> trackMessageSent({
    required String? ticketId,
    required int? attachmentCount,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackMessageSent, [], {
              #ticketId: ticketId,
              #attachmentCount: attachmentCount,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> trackSatisfactionRated({
    required String? ticketId,
    required int? rating,
    required bool? hasComment,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackSatisfactionRated, [], {
              #ticketId: ticketId,
              #rating: rating,
              #hasComment: hasComment,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> trackAttachmentAdded({
    required String? ticketId,
    required String? mimeType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackAttachmentAdded, [], {
              #ticketId: ticketId,
              #mimeType: mimeType,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> trackTicketFiltered({
    required _i4.TicketStatus? statusFilter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackTicketFiltered, [], {
              #statusFilter: statusFilter,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
