// Mocks generated by Mockito 5.4.6 from annotations
// in securityexperts_app/test/features/chat_list/chat_list_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:securityexperts_app/core/logging/app_logger.dart' as _i7;
import 'package:securityexperts_app/data/models/models.dart' as _i4;
import 'package:securityexperts_app/data/repositories/chat/chat_room_repository.dart'
    as _i2;
import 'package:securityexperts_app/features/chat/services/unread_messages_service.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ChatRoomRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatRoomRepository extends _i1.Mock
    implements _i2.ChatRoomRepository {
  MockChatRoomRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Room>> getUserRooms(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserRooms, [userId]),
            returnValue: _i3.Future<List<_i4.Room>>.value(<_i4.Room>[]),
          )
          as _i3.Future<List<_i4.Room>>);

  @override
  _i3.Stream<List<_i4.Room>> getUserRoomsStream(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserRoomsStream, [userId]),
            returnValue: _i3.Stream<List<_i4.Room>>.empty(),
          )
          as _i3.Stream<List<_i4.Room>>);

  @override
  _i3.Future<String> getOrCreateRoom(String? userA, String? userB) =>
      (super.noSuchMethod(
            Invocation.method(#getOrCreateRoom, [userA, userB]),
            returnValue: _i3.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#getOrCreateRoom, [userA, userB]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<void> updateLastMessage({
    required String? roomId,
    required String? lastMessage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateLastMessage, [], {
              #roomId: roomId,
              #lastMessage: lastMessage,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> clearChat(String? roomId) =>
      (super.noSuchMethod(
            Invocation.method(#clearChat, [roomId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> deleteRoom(String? roomId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRoom, [roomId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.Room?> getRoom(String? roomId) =>
      (super.noSuchMethod(
            Invocation.method(#getRoom, [roomId]),
            returnValue: _i3.Future<_i4.Room?>.value(),
          )
          as _i3.Future<_i4.Room?>);
}

/// A class which mocks [UnreadMessagesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUnreadMessagesService extends _i1.Mock
    implements _i6.UnreadMessagesService {
  MockUnreadMessagesService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<int> getTotalUnreadCount() =>
      (super.noSuchMethod(
            Invocation.method(#getTotalUnreadCount, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> getRoomUnreadCount(String? roomId) =>
      (super.noSuchMethod(
            Invocation.method(#getRoomUnreadCount, [roomId]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<void> recalculateTotalUnreadCount() =>
      (super.noSuchMethod(
            Invocation.method(#recalculateTotalUnreadCount, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<int> getTotalUnreadCountStream() =>
      (super.noSuchMethod(
            Invocation.method(#getTotalUnreadCountStream, []),
            returnValue: _i3.Stream<int>.empty(),
          )
          as _i3.Stream<int>);

  @override
  _i3.Stream<int> getRoomUnreadCountStream(String? roomId) =>
      (super.noSuchMethod(
            Invocation.method(#getRoomUnreadCountStream, [roomId]),
            returnValue: _i3.Stream<int>.empty(),
          )
          as _i3.Stream<int>);

  @override
  _i3.Future<void> markRoomAsRead(String? roomId) =>
      (super.noSuchMethod(
            Invocation.method(#markRoomAsRead, [roomId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> markRoomsAsRead(List<String>? roomIds) =>
      (super.noSuchMethod(
            Invocation.method(#markRoomsAsRead, [roomIds]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getRoomsWithUnreadMessages() =>
      (super.noSuchMethod(
            Invocation.method(#getRoomsWithUnreadMessages, []),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [AppLogger].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppLogger extends _i1.Mock implements _i7.AppLogger {
  MockAppLogger() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void verbose(String? message, {String? tag, Map<String, dynamic>? data}) =>
      super.noSuchMethod(
        Invocation.method(#verbose, [message], {#tag: tag, #data: data}),
        returnValueForMissingStub: null,
      );

  @override
  void debug(String? message, {String? tag, Map<String, dynamic>? data}) =>
      super.noSuchMethod(
        Invocation.method(#debug, [message], {#tag: tag, #data: data}),
        returnValueForMissingStub: null,
      );

  @override
  void info(String? message, {String? tag, Map<String, dynamic>? data}) =>
      super.noSuchMethod(
        Invocation.method(#info, [message], {#tag: tag, #data: data}),
        returnValueForMissingStub: null,
      );

  @override
  void warning(String? message, {String? tag, Map<String, dynamic>? data}) =>
      super.noSuchMethod(
        Invocation.method(#warning, [message], {#tag: tag, #data: data}),
        returnValueForMissingStub: null,
      );

  @override
  void error(
    String? message, {
    String? tag,
    dynamic error,
    StackTrace? stackTrace,
    Map<String, dynamic>? data,
  }) => super.noSuchMethod(
    Invocation.method(
      #error,
      [message],
      {#tag: tag, #error: error, #stackTrace: stackTrace, #data: data},
    ),
    returnValueForMissingStub: null,
  );
}
