// Mocks generated by Mockito 5.4.6 from annotations
// in greenhive_app/test/services/account_cleanup_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i12;

import 'package:firebase_messaging/firebase_messaging.dart' as _i8;
import 'package:greenhive_app/core/logging/app_logger.dart' as _i3;
import 'package:greenhive_app/data/models/models.dart' as _i2;
import 'package:greenhive_app/features/calling/infrastructure/repositories/voip_token_repository.dart'
    as _i9;
import 'package:greenhive_app/features/chat/services/user_presence_service.dart'
    as _i6;
import 'package:greenhive_app/features/photo_backup/services/photo_backup_service.dart'
    as _i10;
import 'package:greenhive_app/shared/services/firebase_messaging_service.dart'
    as _i7;
import 'package:greenhive_app/shared/services/user_cache_service.dart' as _i4;
import 'package:greenhive_app/shared/services/user_profile_service.dart'
    as _i11;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUser_0 extends _i1.SmartFake implements _i2.User {
  _FakeUser_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AppLogger].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppLogger extends _i1.Mock implements _i3.AppLogger {
  MockAppLogger() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void verbose(String? message, {String? tag, Map<String, dynamic>? data}) =>
      super.noSuchMethod(
        Invocation.method(#verbose, [message], {#tag: tag, #data: data}),
        returnValueForMissingStub: null,
      );

  @override
  void debug(String? message, {String? tag, Map<String, dynamic>? data}) =>
      super.noSuchMethod(
        Invocation.method(#debug, [message], {#tag: tag, #data: data}),
        returnValueForMissingStub: null,
      );

  @override
  void info(String? message, {String? tag, Map<String, dynamic>? data}) =>
      super.noSuchMethod(
        Invocation.method(#info, [message], {#tag: tag, #data: data}),
        returnValueForMissingStub: null,
      );

  @override
  void warning(String? message, {String? tag, Map<String, dynamic>? data}) =>
      super.noSuchMethod(
        Invocation.method(#warning, [message], {#tag: tag, #data: data}),
        returnValueForMissingStub: null,
      );

  @override
  void error(
    String? message, {
    String? tag,
    dynamic error,
    StackTrace? stackTrace,
    Map<String, dynamic>? data,
  }) => super.noSuchMethod(
    Invocation.method(
      #error,
      [message],
      {#tag: tag, #error: error, #stackTrace: stackTrace, #data: data},
    ),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [UserCacheService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserCacheService extends _i1.Mock implements _i4.UserCacheService {
  MockUserCacheService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get size =>
      (super.noSuchMethod(Invocation.getter(#size), returnValue: 0) as int);

  @override
  _i2.User? get(String? userId) =>
      (super.noSuchMethod(Invocation.method(#get, [userId])) as _i2.User?);

  @override
  _i5.Stream<_i2.User> getUserStream(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserStream, [userId]),
            returnValue: _i5.Stream<_i2.User>.empty(),
          )
          as _i5.Stream<_i2.User>);

  @override
  String? getUserName(String? userId) =>
      (super.noSuchMethod(Invocation.method(#getUserName, [userId]))
          as String?);

  @override
  String? getProfilePictureUrl(String? userId) =>
      (super.noSuchMethod(Invocation.method(#getProfilePictureUrl, [userId]))
          as String?);

  @override
  bool hasProfilePicture(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#hasProfilePicture, [userId]),
            returnValue: false,
          )
          as bool);

  @override
  _i5.Future<_i2.User?> getOrFetch(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getOrFetch, [userId]),
            returnValue: _i5.Future<_i2.User?>.value(),
          )
          as _i5.Future<_i2.User?>);

  @override
  void set(String? userId, _i2.User? user) => super.noSuchMethod(
    Invocation.method(#set, [userId, user]),
    returnValueForMissingStub: null,
  );

  @override
  void setAll(Map<String, _i2.User>? users) => super.noSuchMethod(
    Invocation.method(#setAll, [users]),
    returnValueForMissingStub: null,
  );

  @override
  void loadUsers(List<_i2.User>? users) => super.noSuchMethod(
    Invocation.method(#loadUsers, [users]),
    returnValueForMissingStub: null,
  );

  @override
  bool contains(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#contains, [userId]),
            returnValue: false,
          )
          as bool);

  @override
  Map<String, _i2.User> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: <String, _i2.User>{},
          )
          as Map<String, _i2.User>);

  @override
  Map<String, String> getUserNameMap() =>
      (super.noSuchMethod(
            Invocation.method(#getUserNameMap, []),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  void remove(String? userId) => super.noSuchMethod(
    Invocation.method(#remove, [userId]),
    returnValueForMissingStub: null,
  );

  @override
  void clear() => super.noSuchMethod(
    Invocation.method(#clear, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<Map<String, _i2.User>> fetchMultiple(List<String>? userIds) =>
      (super.noSuchMethod(
            Invocation.method(#fetchMultiple, [userIds]),
            returnValue: _i5.Future<Map<String, _i2.User>>.value(
              <String, _i2.User>{},
            ),
          )
          as _i5.Future<Map<String, _i2.User>>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [UserPresenceService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserPresenceService extends _i1.Mock
    implements _i6.UserPresenceService {
  MockUserPresenceService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  _i5.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> enterChatRoom(String? roomId) =>
      (super.noSuchMethod(
            Invocation.method(#enterChatRoom, [roomId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> leaveChatRoom() =>
      (super.noSuchMethod(
            Invocation.method(#leaveChatRoom, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setAppInForeground() =>
      (super.noSuchMethod(
            Invocation.method(#setAppInForeground, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setAppInBackground() =>
      (super.noSuchMethod(
            Invocation.method(#setAppInBackground, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> clearPresence() =>
      (super.noSuchMethod(
            Invocation.method(#clearPresence, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [FirebaseMessagingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseMessagingService extends _i1.Mock
    implements _i7.FirebaseMessagingService {
  MockFirebaseMessagingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i8.RemoteMessage> get messageStream =>
      (super.noSuchMethod(
            Invocation.getter(#messageStream),
            returnValue: _i5.Stream<_i8.RemoteMessage>.empty(),
          )
          as _i5.Stream<_i8.RemoteMessage>);

  @override
  _i5.Future<void> initialize(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#initialize, [userId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> removeTokenOnLogout() =>
      (super.noSuchMethod(
            Invocation.method(#removeTokenOnLogout, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> subscribeToTopic(String? topic) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToTopic, [topic]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> unsubscribeFromTopic(String? topic) =>
      (super.noSuchMethod(
            Invocation.method(#unsubscribeFromTopic, [topic]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [VoIPTokenRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockVoIPTokenRepository extends _i1.Mock
    implements _i9.VoIPTokenRepository {
  MockVoIPTokenRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> initialize(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#initialize, [userId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String?> getTokenForUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getTokenForUser, [userId]),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<void> clearToken({String? userId}) =>
      (super.noSuchMethod(
            Invocation.method(#clearToken, [], {#userId: userId}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [PhotoBackupService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPhotoBackupService extends _i1.Mock
    implements _i10.PhotoBackupService {
  MockPhotoBackupService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> initialize(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#initialize, [userId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [UserProfileService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserProfileService extends _i1.Mock
    implements _i11.UserProfileService {
  MockUserProfileService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.User get requireUserProfile =>
      (super.noSuchMethod(
            Invocation.getter(#requireUserProfile),
            returnValue: _FakeUser_0(
              this,
              Invocation.getter(#requireUserProfile),
            ),
          )
          as _i2.User);

  @override
  bool get isProfileLoaded =>
      (super.noSuchMethod(
            Invocation.getter(#isProfileLoaded),
            returnValue: false,
          )
          as bool);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void setUserProfile(_i2.User? profile) => super.noSuchMethod(
    Invocation.method(#setUserProfile, [profile]),
    returnValueForMissingStub: null,
  );

  @override
  void updateUserProfile(_i2.User? profile) => super.noSuchMethod(
    Invocation.method(#updateUserProfile, [profile]),
    returnValueForMissingStub: null,
  );

  @override
  void clearUserProfile() => super.noSuchMethod(
    Invocation.method(#clearUserProfile, []),
    returnValueForMissingStub: null,
  );

  @override
  void setLoading(bool? loading) => super.noSuchMethod(
    Invocation.method(#setLoading, [loading]),
    returnValueForMissingStub: null,
  );

  @override
  void setError(String? errorMessage) => super.noSuchMethod(
    Invocation.method(#setError, [errorMessage]),
    returnValueForMissingStub: null,
  );

  @override
  void reset() => super.noSuchMethod(
    Invocation.method(#reset, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
