// Mocks generated by Mockito 5.4.6 from annotations
// in securityexperts_app/test/services/chat_stream_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:securityexperts_app/core/logging/app_logger.dart' as _i6;
import 'package:securityexperts_app/data/models/models.dart' as _i2;
import 'package:securityexperts_app/data/repositories/chat/chat_message_repository.dart'
    as _i3;
import 'package:securityexperts_app/data/repositories/interfaces/repository_interfaces.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMessage_0 extends _i1.SmartFake implements _i2.Message {
  _FakeMessage_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ChatMessageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatMessageRepository extends _i1.Mock
    implements _i3.ChatMessageRepository {
  @override
  _i4.Stream<List<_i2.Message>> getMessagesStream(
    String? roomId, {
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMessagesStream, [roomId], {#limit: limit}),
            returnValue: _i4.Stream<List<_i2.Message>>.empty(),
            returnValueForMissingStub: _i4.Stream<List<_i2.Message>>.empty(),
          )
          as _i4.Stream<List<_i2.Message>>);

  @override
  _i4.Future<(List<_i2.Message>, _i5.PaginationCursor?)>
  getLastMessagesWithCursor(String? roomId, {int? limit = 50}) =>
      (super.noSuchMethod(
            Invocation.method(
              #getLastMessagesWithCursor,
              [roomId],
              {#limit: limit},
            ),
            returnValue:
                _i4.Future<(List<_i2.Message>, _i5.PaginationCursor?)>.value((
                  <_i2.Message>[],
                  null,
                )),
            returnValueForMissingStub:
                _i4.Future<(List<_i2.Message>, _i5.PaginationCursor?)>.value((
                  <_i2.Message>[],
                  null,
                )),
          )
          as _i4.Future<(List<_i2.Message>, _i5.PaginationCursor?)>);

  @override
  _i4.Future<(List<_i2.Message>, _i5.PaginationCursor?)> loadOlderMessages(
    String? roomId, {
    required _i5.PaginationCursor? cursor,
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #loadOlderMessages,
              [roomId],
              {#cursor: cursor, #limit: limit},
            ),
            returnValue:
                _i4.Future<(List<_i2.Message>, _i5.PaginationCursor?)>.value((
                  <_i2.Message>[],
                  null,
                )),
            returnValueForMissingStub:
                _i4.Future<(List<_i2.Message>, _i5.PaginationCursor?)>.value((
                  <_i2.Message>[],
                  null,
                )),
          )
          as _i4.Future<(List<_i2.Message>, _i5.PaginationCursor?)>);

  @override
  _i4.Future<_i2.Message> sendMessage(String? roomId, _i2.Message? message) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [roomId, message]),
            returnValue: _i4.Future<_i2.Message>.value(
              _FakeMessage_0(
                this,
                Invocation.method(#sendMessage, [roomId, message]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.Message>.value(
              _FakeMessage_0(
                this,
                Invocation.method(#sendMessage, [roomId, message]),
              ),
            ),
          )
          as _i4.Future<_i2.Message>);

  @override
  _i4.Future<void> sendCallLogMessage({
    required String? roomId,
    required String? senderId,
    required String? callerId,
    required bool? isVideo,
    required int? durationSeconds,
    required String? status,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendCallLogMessage, [], {
              #roomId: roomId,
              #senderId: senderId,
              #callerId: callerId,
              #isVideo: isVideo,
              #durationSeconds: durationSeconds,
              #status: status,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateMessage(
    String? roomId,
    String? messageId,
    String? newText,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateMessage, [roomId, messageId, newText]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteMessage(String? roomId, String? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMessage, [roomId, messageId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteMessages(String? roomId, List<String>? messageIds) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMessages, [roomId, messageIds]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [AppLogger].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppLogger extends _i1.Mock implements _i6.AppLogger {
  @override
  void verbose(String? message, {String? tag, Map<String, dynamic>? data}) =>
      super.noSuchMethod(
        Invocation.method(#verbose, [message], {#tag: tag, #data: data}),
        returnValueForMissingStub: null,
      );

  @override
  void debug(String? message, {String? tag, Map<String, dynamic>? data}) =>
      super.noSuchMethod(
        Invocation.method(#debug, [message], {#tag: tag, #data: data}),
        returnValueForMissingStub: null,
      );

  @override
  void info(String? message, {String? tag, Map<String, dynamic>? data}) =>
      super.noSuchMethod(
        Invocation.method(#info, [message], {#tag: tag, #data: data}),
        returnValueForMissingStub: null,
      );

  @override
  void warning(String? message, {String? tag, Map<String, dynamic>? data}) =>
      super.noSuchMethod(
        Invocation.method(#warning, [message], {#tag: tag, #data: data}),
        returnValueForMissingStub: null,
      );

  @override
  void error(
    String? message, {
    String? tag,
    dynamic error,
    StackTrace? stackTrace,
    Map<String, dynamic>? data,
  }) => super.noSuchMethod(
    Invocation.method(
      #error,
      [message],
      {#tag: tag, #error: error, #stackTrace: stackTrace, #data: data},
    ),
    returnValueForMissingStub: null,
  );
}
