// Mocks generated by Mockito 5.4.6 from annotations
// in greenhive_app/test/services/firebase_messaging_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:firebase_core/firebase_core.dart' as _i2;
import 'package:firebase_messaging/firebase_messaging.dart' as _i4;
import 'package:firebase_messaging_platform_interface/firebase_messaging_platform_interface.dart'
    as _i3;
import 'package:flutter_local_notifications/flutter_local_notifications.dart'
    as _i7;
import 'package:greenhive_app/core/logging/app_logger.dart' as _i8;
import 'package:greenhive_app/shared/services/notification_service.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFirebaseApp_0 extends _i1.SmartFake implements _i2.FirebaseApp {
  _FakeFirebaseApp_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNotificationSettings_1 extends _i1.SmartFake
    implements _i3.NotificationSettings {
  _FakeNotificationSettings_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FirebaseMessaging].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseMessaging extends _i1.Mock implements _i4.FirebaseMessaging {
  MockFirebaseMessaging() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FirebaseApp get app =>
      (super.noSuchMethod(
            Invocation.getter(#app),
            returnValue: _FakeFirebaseApp_0(this, Invocation.getter(#app)),
          )
          as _i2.FirebaseApp);

  @override
  bool get isAutoInitEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#isAutoInitEnabled),
            returnValue: false,
          )
          as bool);

  @override
  _i5.Stream<String> get onTokenRefresh =>
      (super.noSuchMethod(
            Invocation.getter(#onTokenRefresh),
            returnValue: _i5.Stream<String>.empty(),
          )
          as _i5.Stream<String>);

  @override
  set app(_i2.FirebaseApp? value) => super.noSuchMethod(
    Invocation.setter(#app, value),
    returnValueForMissingStub: null,
  );

  @override
  Map<dynamic, dynamic> get pluginConstants =>
      (super.noSuchMethod(
            Invocation.getter(#pluginConstants),
            returnValue: <dynamic, dynamic>{},
          )
          as Map<dynamic, dynamic>);

  @override
  _i5.Future<_i3.RemoteMessage?> getInitialMessage() =>
      (super.noSuchMethod(
            Invocation.method(#getInitialMessage, []),
            returnValue: _i5.Future<_i3.RemoteMessage?>.value(),
          )
          as _i5.Future<_i3.RemoteMessage?>);

  @override
  _i5.Future<void> deleteToken() =>
      (super.noSuchMethod(
            Invocation.method(#deleteToken, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String?> getAPNSToken() =>
      (super.noSuchMethod(
            Invocation.method(#getAPNSToken, []),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<String?> getToken({String? vapidKey}) =>
      (super.noSuchMethod(
            Invocation.method(#getToken, [], {#vapidKey: vapidKey}),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<bool> isSupported() =>
      (super.noSuchMethod(
            Invocation.method(#isSupported, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<_i3.NotificationSettings> getNotificationSettings() =>
      (super.noSuchMethod(
            Invocation.method(#getNotificationSettings, []),
            returnValue: _i5.Future<_i3.NotificationSettings>.value(
              _FakeNotificationSettings_1(
                this,
                Invocation.method(#getNotificationSettings, []),
              ),
            ),
          )
          as _i5.Future<_i3.NotificationSettings>);

  @override
  _i5.Future<_i3.NotificationSettings> requestPermission({
    bool? alert = true,
    bool? announcement = false,
    bool? badge = true,
    bool? carPlay = false,
    bool? criticalAlert = false,
    bool? provisional = false,
    bool? sound = true,
    bool? providesAppNotificationSettings = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#requestPermission, [], {
              #alert: alert,
              #announcement: announcement,
              #badge: badge,
              #carPlay: carPlay,
              #criticalAlert: criticalAlert,
              #provisional: provisional,
              #sound: sound,
              #providesAppNotificationSettings: providesAppNotificationSettings,
            }),
            returnValue: _i5.Future<_i3.NotificationSettings>.value(
              _FakeNotificationSettings_1(
                this,
                Invocation.method(#requestPermission, [], {
                  #alert: alert,
                  #announcement: announcement,
                  #badge: badge,
                  #carPlay: carPlay,
                  #criticalAlert: criticalAlert,
                  #provisional: provisional,
                  #sound: sound,
                  #providesAppNotificationSettings:
                      providesAppNotificationSettings,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.NotificationSettings>);

  @override
  _i5.Future<void> setAutoInitEnabled(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setAutoInitEnabled, [enabled]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setDeliveryMetricsExportToBigQuery(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setDeliveryMetricsExportToBigQuery, [enabled]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setForegroundNotificationPresentationOptions({
    bool? alert = false,
    bool? badge = false,
    bool? sound = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setForegroundNotificationPresentationOptions,
              [],
              {#alert: alert, #badge: badge, #sound: sound},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> subscribeToTopic(String? topic) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToTopic, [topic]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> unsubscribeFromTopic(String? topic) =>
      (super.noSuchMethod(
            Invocation.method(#unsubscribeFromTopic, [topic]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i6.NotificationService {
  MockNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> showNotification({
    required String? title,
    required String? body,
    String? channelId,
    Map<String, String>? payload,
    int? notificationId = 1,
    String? groupKey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#showNotification, [], {
              #title: title,
              #body: body,
              #channelId: channelId,
              #payload: payload,
              #notificationId: notificationId,
              #groupKey: groupKey,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> showIncomingCallNotification({
    required String? callerName,
    required String? callerId,
    required String? roomId,
    bool? isVideo = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#showIncomingCallNotification, [], {
              #callerName: callerName,
              #callerId: callerId,
              #roomId: roomId,
              #isVideo: isVideo,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> showNewMessageNotification({
    required String? senderName,
    required String? senderId,
    required String? message,
    required String? roomId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#showNewMessageNotification, [], {
              #senderName: senderName,
              #senderId: senderId,
              #message: message,
              #roomId: roomId,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> showExpertRequestNotification({
    required String? requesterName,
    required String? requesterId,
    required String? requestId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#showExpertRequestNotification, [], {
              #requesterName: requesterName,
              #requesterId: requesterId,
              #requestId: requestId,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> cancelNotification(int? notificationId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelNotification, [notificationId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> cancelAllNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#cancelAllNotifications, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i7.PendingNotificationRequest>> getPendingNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingNotifications, []),
            returnValue: _i5.Future<List<_i7.PendingNotificationRequest>>.value(
              <_i7.PendingNotificationRequest>[],
            ),
          )
          as _i5.Future<List<_i7.PendingNotificationRequest>>);

  @override
  _i5.Future<void> clearBadge() =>
      (super.noSuchMethod(
            Invocation.method(#clearBadge, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setBadge(int? count) =>
      (super.noSuchMethod(
            Invocation.method(#setBadge, [count]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<int> incrementBadge([int? count = 1]) =>
      (super.noSuchMethod(
            Invocation.method(#incrementBadge, [count]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> getBadge() =>
      (super.noSuchMethod(
            Invocation.method(#getBadge, []),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);
}

/// A class which mocks [AppLogger].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppLogger extends _i1.Mock implements _i8.AppLogger {
  MockAppLogger() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void verbose(String? message, {String? tag, Map<String, dynamic>? data}) =>
      super.noSuchMethod(
        Invocation.method(#verbose, [message], {#tag: tag, #data: data}),
        returnValueForMissingStub: null,
      );

  @override
  void debug(String? message, {String? tag, Map<String, dynamic>? data}) =>
      super.noSuchMethod(
        Invocation.method(#debug, [message], {#tag: tag, #data: data}),
        returnValueForMissingStub: null,
      );

  @override
  void info(String? message, {String? tag, Map<String, dynamic>? data}) =>
      super.noSuchMethod(
        Invocation.method(#info, [message], {#tag: tag, #data: data}),
        returnValueForMissingStub: null,
      );

  @override
  void warning(String? message, {String? tag, Map<String, dynamic>? data}) =>
      super.noSuchMethod(
        Invocation.method(#warning, [message], {#tag: tag, #data: data}),
        returnValueForMissingStub: null,
      );

  @override
  void error(
    String? message, {
    String? tag,
    dynamic error,
    StackTrace? stackTrace,
    Map<String, dynamic>? data,
  }) => super.noSuchMethod(
    Invocation.method(
      #error,
      [message],
      {#tag: tag, #error: error, #stackTrace: stackTrace, #data: data},
    ),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [RemoteMessage].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteMessage extends _i1.Mock implements _i3.RemoteMessage {
  MockRemoteMessage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get contentAvailable =>
      (super.noSuchMethod(
            Invocation.getter(#contentAvailable),
            returnValue: false,
          )
          as bool);

  @override
  Map<String, dynamic> get data =>
      (super.noSuchMethod(
            Invocation.getter(#data),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  bool get mutableContent =>
      (super.noSuchMethod(
            Invocation.getter(#mutableContent),
            returnValue: false,
          )
          as bool);

  @override
  Map<String, dynamic> toMap() =>
      (super.noSuchMethod(
            Invocation.method(#toMap, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}

/// A class which mocks [NotificationSettings].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationSettings extends _i1.Mock
    implements _i3.NotificationSettings {
  MockNotificationSettings() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.AppleNotificationSetting get alert =>
      (super.noSuchMethod(
            Invocation.getter(#alert),
            returnValue: _i3.AppleNotificationSetting.disabled,
          )
          as _i3.AppleNotificationSetting);

  @override
  _i3.AppleNotificationSetting get announcement =>
      (super.noSuchMethod(
            Invocation.getter(#announcement),
            returnValue: _i3.AppleNotificationSetting.disabled,
          )
          as _i3.AppleNotificationSetting);

  @override
  _i3.AuthorizationStatus get authorizationStatus =>
      (super.noSuchMethod(
            Invocation.getter(#authorizationStatus),
            returnValue: _i3.AuthorizationStatus.authorized,
          )
          as _i3.AuthorizationStatus);

  @override
  _i3.AppleNotificationSetting get timeSensitive =>
      (super.noSuchMethod(
            Invocation.getter(#timeSensitive),
            returnValue: _i3.AppleNotificationSetting.disabled,
          )
          as _i3.AppleNotificationSetting);

  @override
  _i3.AppleNotificationSetting get criticalAlert =>
      (super.noSuchMethod(
            Invocation.getter(#criticalAlert),
            returnValue: _i3.AppleNotificationSetting.disabled,
          )
          as _i3.AppleNotificationSetting);

  @override
  _i3.AppleNotificationSetting get badge =>
      (super.noSuchMethod(
            Invocation.getter(#badge),
            returnValue: _i3.AppleNotificationSetting.disabled,
          )
          as _i3.AppleNotificationSetting);

  @override
  _i3.AppleNotificationSetting get carPlay =>
      (super.noSuchMethod(
            Invocation.getter(#carPlay),
            returnValue: _i3.AppleNotificationSetting.disabled,
          )
          as _i3.AppleNotificationSetting);

  @override
  _i3.AppleNotificationSetting get lockScreen =>
      (super.noSuchMethod(
            Invocation.getter(#lockScreen),
            returnValue: _i3.AppleNotificationSetting.disabled,
          )
          as _i3.AppleNotificationSetting);

  @override
  _i3.AppleNotificationSetting get notificationCenter =>
      (super.noSuchMethod(
            Invocation.getter(#notificationCenter),
            returnValue: _i3.AppleNotificationSetting.disabled,
          )
          as _i3.AppleNotificationSetting);

  @override
  _i3.AppleShowPreviewSetting get showPreviews =>
      (super.noSuchMethod(
            Invocation.getter(#showPreviews),
            returnValue: _i3.AppleShowPreviewSetting.always,
          )
          as _i3.AppleShowPreviewSetting);

  @override
  _i3.AppleNotificationSetting get sound =>
      (super.noSuchMethod(
            Invocation.getter(#sound),
            returnValue: _i3.AppleNotificationSetting.disabled,
          )
          as _i3.AppleNotificationSetting);

  @override
  _i3.AppleNotificationSetting get providesAppNotificationSettings =>
      (super.noSuchMethod(
            Invocation.getter(#providesAppNotificationSettings),
            returnValue: _i3.AppleNotificationSetting.disabled,
          )
          as _i3.AppleNotificationSetting);
}

/// A class which mocks [RemoteNotification].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteNotification extends _i1.Mock
    implements _i3.RemoteNotification {
  MockRemoteNotification() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<String> get titleLocArgs =>
      (super.noSuchMethod(
            Invocation.getter(#titleLocArgs),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  List<String> get bodyLocArgs =>
      (super.noSuchMethod(
            Invocation.getter(#bodyLocArgs),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  Map<String, dynamic> toMap() =>
      (super.noSuchMethod(
            Invocation.method(#toMap, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}
