// Mocks generated by Mockito 5.4.6 from annotations
// in greenhive_app/test/services/media_upload_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i16;
import 'dart:typed_data' as _i15;

import 'package:firebase_auth/firebase_auth.dart' as _i7;
import 'package:firebase_auth_platform_interface/firebase_auth_platform_interface.dart'
    as _i6;
import 'package:firebase_core/firebase_core.dart' as _i5;
import 'package:firebase_performance/firebase_performance.dart' as _i3;
import 'package:firebase_storage/firebase_storage.dart' as _i8;
import 'package:firebase_storage_platform_interface/firebase_storage_platform_interface.dart'
    as _i9;
import 'package:greenhive_app/core/analytics/analytics_service.dart' as _i12;
import 'package:greenhive_app/core/logging/app_logger.dart' as _i14;
import 'package:greenhive_app/data/models/models.dart' as _i2;
import 'package:greenhive_app/data/repositories/chat/chat_message_repository.dart'
    as _i10;
import 'package:greenhive_app/data/repositories/interfaces/repository_interfaces.dart'
    as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i13;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMessage_0 extends _i1.SmartFake implements _i2.Message {
  _FakeMessage_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTrace_1 extends _i1.SmartFake implements _i3.Trace {
  _FakeTrace_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHttpMetric_2 extends _i1.SmartFake implements _i3.HttpMetric {
  _FakeHttpMetric_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_3<T1> extends _i1.SmartFake implements _i4.Future<T1> {
  _FakeFuture_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFirebaseApp_4 extends _i1.SmartFake implements _i5.FirebaseApp {
  _FakeFirebaseApp_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeActionCodeInfo_5 extends _i1.SmartFake
    implements _i6.ActionCodeInfo {
  _FakeActionCodeInfo_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserCredential_6 extends _i1.SmartFake
    implements _i7.UserCredential {
  _FakeUserCredential_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConfirmationResult_7 extends _i1.SmartFake
    implements _i7.ConfirmationResult {
  _FakeConfirmationResult_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePasswordValidationStatus_8 extends _i1.SmartFake
    implements _i6.PasswordValidationStatus {
  _FakePasswordValidationStatus_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserMetadata_9 extends _i1.SmartFake implements _i6.UserMetadata {
  _FakeUserMetadata_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMultiFactor_10 extends _i1.SmartFake implements _i7.MultiFactor {
  _FakeMultiFactor_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIdTokenResult_11 extends _i1.SmartFake implements _i6.IdTokenResult {
  _FakeIdTokenResult_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUser_12 extends _i1.SmartFake implements _i7.User {
  _FakeUser_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDuration_13 extends _i1.SmartFake implements Duration {
  _FakeDuration_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeReference_14 extends _i1.SmartFake implements _i8.Reference {
  _FakeReference_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFirebaseStorage_15 extends _i1.SmartFake
    implements _i8.FirebaseStorage {
  _FakeFirebaseStorage_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFullMetadata_16 extends _i1.SmartFake implements _i9.FullMetadata {
  _FakeFullMetadata_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeListResult_17 extends _i1.SmartFake implements _i8.ListResult {
  _FakeListResult_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUploadTask_18 extends _i1.SmartFake implements _i8.UploadTask {
  _FakeUploadTask_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDownloadTask_19 extends _i1.SmartFake implements _i8.DownloadTask {
  _FakeDownloadTask_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTaskSnapshot_20 extends _i1.SmartFake implements _i8.TaskSnapshot {
  _FakeTaskSnapshot_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ChatMessageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatMessageRepository extends _i1.Mock
    implements _i10.ChatMessageRepository {
  MockChatMessageRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<List<_i2.Message>> getMessagesStream(
    String? roomId, {
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMessagesStream, [roomId], {#limit: limit}),
            returnValue: _i4.Stream<List<_i2.Message>>.empty(),
          )
          as _i4.Stream<List<_i2.Message>>);

  @override
  _i4.Future<(List<_i2.Message>, _i11.PaginationCursor?)>
  getLastMessagesWithCursor(String? roomId, {int? limit = 50}) =>
      (super.noSuchMethod(
            Invocation.method(
              #getLastMessagesWithCursor,
              [roomId],
              {#limit: limit},
            ),
            returnValue:
                _i4.Future<(List<_i2.Message>, _i11.PaginationCursor?)>.value((
                  <_i2.Message>[],
                  null,
                )),
          )
          as _i4.Future<(List<_i2.Message>, _i11.PaginationCursor?)>);

  @override
  _i4.Future<(List<_i2.Message>, _i11.PaginationCursor?)> loadOlderMessages(
    String? roomId, {
    required _i11.PaginationCursor? cursor,
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #loadOlderMessages,
              [roomId],
              {#cursor: cursor, #limit: limit},
            ),
            returnValue:
                _i4.Future<(List<_i2.Message>, _i11.PaginationCursor?)>.value((
                  <_i2.Message>[],
                  null,
                )),
          )
          as _i4.Future<(List<_i2.Message>, _i11.PaginationCursor?)>);

  @override
  _i4.Future<_i2.Message> sendMessage(String? roomId, _i2.Message? message) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [roomId, message]),
            returnValue: _i4.Future<_i2.Message>.value(
              _FakeMessage_0(
                this,
                Invocation.method(#sendMessage, [roomId, message]),
              ),
            ),
          )
          as _i4.Future<_i2.Message>);

  @override
  _i4.Future<void> sendCallLogMessage({
    required String? roomId,
    required String? senderId,
    required String? callerId,
    required bool? isVideo,
    required int? durationSeconds,
    required String? status,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendCallLogMessage, [], {
              #roomId: roomId,
              #senderId: senderId,
              #callerId: callerId,
              #isVideo: isVideo,
              #durationSeconds: durationSeconds,
              #status: status,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateMessage(
    String? roomId,
    String? messageId,
    String? newText,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateMessage, [roomId, messageId, newText]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteMessage(String? roomId, String? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMessage, [roomId, messageId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteMessages(String? roomId, List<String>? messageIds) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMessages, [roomId, messageIds]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [AnalyticsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalyticsService extends _i1.Mock implements _i12.AnalyticsService {
  MockAnalyticsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logEvent(String? name, {Map<String, Object>? parameters}) =>
      (super.noSuchMethod(
            Invocation.method(#logEvent, [name], {#parameters: parameters}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logScreenView({
    required String? screenName,
    String? screenClass,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logScreenView, [], {
              #screenName: screenName,
              #screenClass: screenClass,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setUserProperty({
    required String? name,
    required String? value,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setUserProperty, [], {
              #name: name,
              #value: value,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setUserId(String? hashedUserId) =>
      (super.noSuchMethod(
            Invocation.method(#setUserId, [hashedUserId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setUserOnLogin({
    required String? userId,
    required bool? isExpert,
    DateTime? accountCreatedAt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setUserOnLogin, [], {
              #userId: userId,
              #isExpert: isExpert,
              #accountCreatedAt: accountCreatedAt,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setUserContext({
    required String? userType,
    required String? accountStatus,
    required String? platform,
    required String? appVersion,
    bool? isExpertVerified,
    String? accountAgeBucket,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setUserContext, [], {
              #userType: userType,
              #accountStatus: accountStatus,
              #platform: platform,
              #appVersion: appVersion,
              #isExpertVerified: isExpertVerified,
              #accountAgeBucket: accountAgeBucket,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i3.Trace newTrace(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#newTrace, [name]),
            returnValue: _FakeTrace_1(
              this,
              Invocation.method(#newTrace, [name]),
            ),
          )
          as _i3.Trace);

  @override
  _i3.HttpMetric newHttpMetric(String? url, _i3.HttpMethod? method) =>
      (super.noSuchMethod(
            Invocation.method(#newHttpMetric, [url, method]),
            returnValue: _FakeHttpMetric_2(
              this,
              Invocation.method(#newHttpMetric, [url, method]),
            ),
          )
          as _i3.HttpMetric);

  @override
  _i4.Future<T> traceAsync<T>(
    String? traceName,
    _i4.Future<T> Function()? operation, {
    Map<String, String>? attributes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #traceAsync,
              [traceName, operation],
              {#attributes: attributes},
            ),
            returnValue:
                _i13.ifNotNull(
                  _i13.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #traceAsync,
                      [traceName, operation],
                      {#attributes: attributes},
                    ),
                  ),
                  (T v) => _i4.Future<T>.value(v),
                ) ??
                _FakeFuture_3<T>(
                  this,
                  Invocation.method(
                    #traceAsync,
                    [traceName, operation],
                    {#attributes: attributes},
                  ),
                ),
          )
          as _i4.Future<T>);

  @override
  _i4.Future<void> setCrashlyticsKey(String? key, dynamic value) =>
      (super.noSuchMethod(
            Invocation.method(#setCrashlyticsKey, [key, value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void logBreadcrumb(String? feature, String? action) => super.noSuchMethod(
    Invocation.method(#logBreadcrumb, [feature, action]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> setFeatureContext(String? feature, String? screen) =>
      (super.noSuchMethod(
            Invocation.method(#setFeatureContext, [feature, screen]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> recordError({
    required dynamic error,
    required StackTrace? stackTrace,
    required String? feature,
    required String? operation,
    Map<String, String>? metadata,
    bool? fatal = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#recordError, [], {
              #error: error,
              #stackTrace: stackTrace,
              #feature: feature,
              #operation: operation,
              #metadata: metadata,
              #fatal: fatal,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [AppLogger].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppLogger extends _i1.Mock implements _i14.AppLogger {
  MockAppLogger() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void verbose(String? message, {String? tag, Map<String, dynamic>? data}) =>
      super.noSuchMethod(
        Invocation.method(#verbose, [message], {#tag: tag, #data: data}),
        returnValueForMissingStub: null,
      );

  @override
  void debug(String? message, {String? tag, Map<String, dynamic>? data}) =>
      super.noSuchMethod(
        Invocation.method(#debug, [message], {#tag: tag, #data: data}),
        returnValueForMissingStub: null,
      );

  @override
  void info(String? message, {String? tag, Map<String, dynamic>? data}) =>
      super.noSuchMethod(
        Invocation.method(#info, [message], {#tag: tag, #data: data}),
        returnValueForMissingStub: null,
      );

  @override
  void warning(String? message, {String? tag, Map<String, dynamic>? data}) =>
      super.noSuchMethod(
        Invocation.method(#warning, [message], {#tag: tag, #data: data}),
        returnValueForMissingStub: null,
      );

  @override
  void error(
    String? message, {
    String? tag,
    dynamic error,
    StackTrace? stackTrace,
    Map<String, dynamic>? data,
  }) => super.noSuchMethod(
    Invocation.method(
      #error,
      [message],
      {#tag: tag, #error: error, #stackTrace: stackTrace, #data: data},
    ),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [FirebaseAuth].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseAuth extends _i1.Mock implements _i7.FirebaseAuth {
  MockFirebaseAuth() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.FirebaseApp get app =>
      (super.noSuchMethod(
            Invocation.getter(#app),
            returnValue: _FakeFirebaseApp_4(this, Invocation.getter(#app)),
          )
          as _i5.FirebaseApp);

  @override
  set app(_i5.FirebaseApp? value) => super.noSuchMethod(
    Invocation.setter(#app, value),
    returnValueForMissingStub: null,
  );

  @override
  set tenantId(String? tenantId) => super.noSuchMethod(
    Invocation.setter(#tenantId, tenantId),
    returnValueForMissingStub: null,
  );

  @override
  set customAuthDomain(String? customAuthDomain) => super.noSuchMethod(
    Invocation.setter(#customAuthDomain, customAuthDomain),
    returnValueForMissingStub: null,
  );

  @override
  Map<dynamic, dynamic> get pluginConstants =>
      (super.noSuchMethod(
            Invocation.getter(#pluginConstants),
            returnValue: <dynamic, dynamic>{},
          )
          as Map<dynamic, dynamic>);

  @override
  _i4.Future<void> useAuthEmulator(
    String? host,
    int? port, {
    bool? automaticHostMapping = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #useAuthEmulator,
              [host, port],
              {#automaticHostMapping: automaticHostMapping},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> applyActionCode(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#applyActionCode, [code]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i6.ActionCodeInfo> checkActionCode(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#checkActionCode, [code]),
            returnValue: _i4.Future<_i6.ActionCodeInfo>.value(
              _FakeActionCodeInfo_5(
                this,
                Invocation.method(#checkActionCode, [code]),
              ),
            ),
          )
          as _i4.Future<_i6.ActionCodeInfo>);

  @override
  _i4.Future<void> confirmPasswordReset({
    required String? code,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#confirmPasswordReset, [], {
              #code: code,
              #newPassword: newPassword,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i7.UserCredential> createUserWithEmailAndPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createUserWithEmailAndPassword, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i4.Future<_i7.UserCredential>.value(
              _FakeUserCredential_6(
                this,
                Invocation.method(#createUserWithEmailAndPassword, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i4.Future<_i7.UserCredential>);

  @override
  _i4.Future<_i7.UserCredential> getRedirectResult() =>
      (super.noSuchMethod(
            Invocation.method(#getRedirectResult, []),
            returnValue: _i4.Future<_i7.UserCredential>.value(
              _FakeUserCredential_6(
                this,
                Invocation.method(#getRedirectResult, []),
              ),
            ),
          )
          as _i4.Future<_i7.UserCredential>);

  @override
  bool isSignInWithEmailLink(String? emailLink) =>
      (super.noSuchMethod(
            Invocation.method(#isSignInWithEmailLink, [emailLink]),
            returnValue: false,
          )
          as bool);

  @override
  _i4.Stream<_i7.User?> authStateChanges() =>
      (super.noSuchMethod(
            Invocation.method(#authStateChanges, []),
            returnValue: _i4.Stream<_i7.User?>.empty(),
          )
          as _i4.Stream<_i7.User?>);

  @override
  _i4.Stream<_i7.User?> idTokenChanges() =>
      (super.noSuchMethod(
            Invocation.method(#idTokenChanges, []),
            returnValue: _i4.Stream<_i7.User?>.empty(),
          )
          as _i4.Stream<_i7.User?>);

  @override
  _i4.Stream<_i7.User?> userChanges() =>
      (super.noSuchMethod(
            Invocation.method(#userChanges, []),
            returnValue: _i4.Stream<_i7.User?>.empty(),
          )
          as _i4.Stream<_i7.User?>);

  @override
  _i4.Future<void> sendPasswordResetEmail({
    required String? email,
    _i6.ActionCodeSettings? actionCodeSettings,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordResetEmail, [], {
              #email: email,
              #actionCodeSettings: actionCodeSettings,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> sendSignInLinkToEmail({
    required String? email,
    required _i6.ActionCodeSettings? actionCodeSettings,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendSignInLinkToEmail, [], {
              #email: email,
              #actionCodeSettings: actionCodeSettings,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setLanguageCode(String? languageCode) =>
      (super.noSuchMethod(
            Invocation.method(#setLanguageCode, [languageCode]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setSettings({
    bool? appVerificationDisabledForTesting = false,
    String? userAccessGroup,
    String? phoneNumber,
    String? smsCode,
    bool? forceRecaptchaFlow,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setSettings, [], {
              #appVerificationDisabledForTesting:
                  appVerificationDisabledForTesting,
              #userAccessGroup: userAccessGroup,
              #phoneNumber: phoneNumber,
              #smsCode: smsCode,
              #forceRecaptchaFlow: forceRecaptchaFlow,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setPersistence(_i6.Persistence? persistence) =>
      (super.noSuchMethod(
            Invocation.method(#setPersistence, [persistence]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i7.UserCredential> signInAnonymously() =>
      (super.noSuchMethod(
            Invocation.method(#signInAnonymously, []),
            returnValue: _i4.Future<_i7.UserCredential>.value(
              _FakeUserCredential_6(
                this,
                Invocation.method(#signInAnonymously, []),
              ),
            ),
          )
          as _i4.Future<_i7.UserCredential>);

  @override
  _i4.Future<_i7.UserCredential> signInWithCredential(
    _i6.AuthCredential? credential,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithCredential, [credential]),
            returnValue: _i4.Future<_i7.UserCredential>.value(
              _FakeUserCredential_6(
                this,
                Invocation.method(#signInWithCredential, [credential]),
              ),
            ),
          )
          as _i4.Future<_i7.UserCredential>);

  @override
  _i4.Future<_i7.UserCredential> signInWithCustomToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithCustomToken, [token]),
            returnValue: _i4.Future<_i7.UserCredential>.value(
              _FakeUserCredential_6(
                this,
                Invocation.method(#signInWithCustomToken, [token]),
              ),
            ),
          )
          as _i4.Future<_i7.UserCredential>);

  @override
  _i4.Future<_i7.UserCredential> signInWithEmailAndPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmailAndPassword, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i4.Future<_i7.UserCredential>.value(
              _FakeUserCredential_6(
                this,
                Invocation.method(#signInWithEmailAndPassword, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i4.Future<_i7.UserCredential>);

  @override
  _i4.Future<_i7.UserCredential> signInWithEmailLink({
    required String? email,
    required String? emailLink,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmailLink, [], {
              #email: email,
              #emailLink: emailLink,
            }),
            returnValue: _i4.Future<_i7.UserCredential>.value(
              _FakeUserCredential_6(
                this,
                Invocation.method(#signInWithEmailLink, [], {
                  #email: email,
                  #emailLink: emailLink,
                }),
              ),
            ),
          )
          as _i4.Future<_i7.UserCredential>);

  @override
  _i4.Future<_i7.UserCredential> signInWithProvider(
    _i6.AuthProvider? provider,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithProvider, [provider]),
            returnValue: _i4.Future<_i7.UserCredential>.value(
              _FakeUserCredential_6(
                this,
                Invocation.method(#signInWithProvider, [provider]),
              ),
            ),
          )
          as _i4.Future<_i7.UserCredential>);

  @override
  _i4.Future<_i7.ConfirmationResult> signInWithPhoneNumber(
    String? phoneNumber, [
    _i7.RecaptchaVerifier? verifier,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithPhoneNumber, [phoneNumber, verifier]),
            returnValue: _i4.Future<_i7.ConfirmationResult>.value(
              _FakeConfirmationResult_7(
                this,
                Invocation.method(#signInWithPhoneNumber, [
                  phoneNumber,
                  verifier,
                ]),
              ),
            ),
          )
          as _i4.Future<_i7.ConfirmationResult>);

  @override
  _i4.Future<_i7.UserCredential> signInWithPopup(_i6.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithPopup, [provider]),
            returnValue: _i4.Future<_i7.UserCredential>.value(
              _FakeUserCredential_6(
                this,
                Invocation.method(#signInWithPopup, [provider]),
              ),
            ),
          )
          as _i4.Future<_i7.UserCredential>);

  @override
  _i4.Future<void> signInWithRedirect(_i6.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithRedirect, [provider]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String> verifyPasswordResetCode(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#verifyPasswordResetCode, [code]),
            returnValue: _i4.Future<String>.value(
              _i13.dummyValue<String>(
                this,
                Invocation.method(#verifyPasswordResetCode, [code]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<void> verifyPhoneNumber({
    String? phoneNumber,
    _i6.PhoneMultiFactorInfo? multiFactorInfo,
    required _i6.PhoneVerificationCompleted? verificationCompleted,
    required _i6.PhoneVerificationFailed? verificationFailed,
    required _i6.PhoneCodeSent? codeSent,
    required _i6.PhoneCodeAutoRetrievalTimeout? codeAutoRetrievalTimeout,
    String? autoRetrievedSmsCodeForTesting,
    Duration? timeout = const Duration(seconds: 30),
    int? forceResendingToken,
    _i6.MultiFactorSession? multiFactorSession,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyPhoneNumber, [], {
              #phoneNumber: phoneNumber,
              #multiFactorInfo: multiFactorInfo,
              #verificationCompleted: verificationCompleted,
              #verificationFailed: verificationFailed,
              #codeSent: codeSent,
              #codeAutoRetrievalTimeout: codeAutoRetrievalTimeout,
              #autoRetrievedSmsCodeForTesting: autoRetrievedSmsCodeForTesting,
              #timeout: timeout,
              #forceResendingToken: forceResendingToken,
              #multiFactorSession: multiFactorSession,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> revokeTokenWithAuthorizationCode(
    String? authorizationCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#revokeTokenWithAuthorizationCode, [
              authorizationCode,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> initializeRecaptchaConfig() =>
      (super.noSuchMethod(
            Invocation.method(#initializeRecaptchaConfig, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i6.PasswordValidationStatus> validatePassword(
    _i7.FirebaseAuth? auth,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#validatePassword, [auth, password]),
            returnValue: _i4.Future<_i6.PasswordValidationStatus>.value(
              _FakePasswordValidationStatus_8(
                this,
                Invocation.method(#validatePassword, [auth, password]),
              ),
            ),
          )
          as _i4.Future<_i6.PasswordValidationStatus>);
}

/// A class which mocks [User].
///
/// See the documentation for Mockito's code generation for more information.
class MockUser extends _i1.Mock implements _i7.User {
  MockUser() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get emailVerified =>
      (super.noSuchMethod(Invocation.getter(#emailVerified), returnValue: false)
          as bool);

  @override
  bool get isAnonymous =>
      (super.noSuchMethod(Invocation.getter(#isAnonymous), returnValue: false)
          as bool);

  @override
  _i6.UserMetadata get metadata =>
      (super.noSuchMethod(
            Invocation.getter(#metadata),
            returnValue: _FakeUserMetadata_9(
              this,
              Invocation.getter(#metadata),
            ),
          )
          as _i6.UserMetadata);

  @override
  List<_i6.UserInfo> get providerData =>
      (super.noSuchMethod(
            Invocation.getter(#providerData),
            returnValue: <_i6.UserInfo>[],
          )
          as List<_i6.UserInfo>);

  @override
  String get uid =>
      (super.noSuchMethod(
            Invocation.getter(#uid),
            returnValue: _i13.dummyValue<String>(this, Invocation.getter(#uid)),
          )
          as String);

  @override
  _i7.MultiFactor get multiFactor =>
      (super.noSuchMethod(
            Invocation.getter(#multiFactor),
            returnValue: _FakeMultiFactor_10(
              this,
              Invocation.getter(#multiFactor),
            ),
          )
          as _i7.MultiFactor);

  @override
  _i4.Future<void> delete() =>
      (super.noSuchMethod(
            Invocation.method(#delete, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getIdToken([bool? forceRefresh = false]) =>
      (super.noSuchMethod(
            Invocation.method(#getIdToken, [forceRefresh]),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<_i6.IdTokenResult> getIdTokenResult([
    bool? forceRefresh = false,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#getIdTokenResult, [forceRefresh]),
            returnValue: _i4.Future<_i6.IdTokenResult>.value(
              _FakeIdTokenResult_11(
                this,
                Invocation.method(#getIdTokenResult, [forceRefresh]),
              ),
            ),
          )
          as _i4.Future<_i6.IdTokenResult>);

  @override
  _i4.Future<_i7.UserCredential> linkWithCredential(
    _i6.AuthCredential? credential,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithCredential, [credential]),
            returnValue: _i4.Future<_i7.UserCredential>.value(
              _FakeUserCredential_6(
                this,
                Invocation.method(#linkWithCredential, [credential]),
              ),
            ),
          )
          as _i4.Future<_i7.UserCredential>);

  @override
  _i4.Future<_i7.UserCredential> linkWithProvider(_i6.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithProvider, [provider]),
            returnValue: _i4.Future<_i7.UserCredential>.value(
              _FakeUserCredential_6(
                this,
                Invocation.method(#linkWithProvider, [provider]),
              ),
            ),
          )
          as _i4.Future<_i7.UserCredential>);

  @override
  _i4.Future<_i7.UserCredential> reauthenticateWithProvider(
    _i6.AuthProvider? provider,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithProvider, [provider]),
            returnValue: _i4.Future<_i7.UserCredential>.value(
              _FakeUserCredential_6(
                this,
                Invocation.method(#reauthenticateWithProvider, [provider]),
              ),
            ),
          )
          as _i4.Future<_i7.UserCredential>);

  @override
  _i4.Future<_i7.UserCredential> reauthenticateWithPopup(
    _i6.AuthProvider? provider,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithPopup, [provider]),
            returnValue: _i4.Future<_i7.UserCredential>.value(
              _FakeUserCredential_6(
                this,
                Invocation.method(#reauthenticateWithPopup, [provider]),
              ),
            ),
          )
          as _i4.Future<_i7.UserCredential>);

  @override
  _i4.Future<void> reauthenticateWithRedirect(_i6.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithRedirect, [provider]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i7.UserCredential> linkWithPopup(_i6.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithPopup, [provider]),
            returnValue: _i4.Future<_i7.UserCredential>.value(
              _FakeUserCredential_6(
                this,
                Invocation.method(#linkWithPopup, [provider]),
              ),
            ),
          )
          as _i4.Future<_i7.UserCredential>);

  @override
  _i4.Future<void> linkWithRedirect(_i6.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithRedirect, [provider]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i7.ConfirmationResult> linkWithPhoneNumber(
    String? phoneNumber, [
    _i7.RecaptchaVerifier? verifier,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithPhoneNumber, [phoneNumber, verifier]),
            returnValue: _i4.Future<_i7.ConfirmationResult>.value(
              _FakeConfirmationResult_7(
                this,
                Invocation.method(#linkWithPhoneNumber, [
                  phoneNumber,
                  verifier,
                ]),
              ),
            ),
          )
          as _i4.Future<_i7.ConfirmationResult>);

  @override
  _i4.Future<_i7.UserCredential> reauthenticateWithCredential(
    _i6.AuthCredential? credential,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithCredential, [credential]),
            returnValue: _i4.Future<_i7.UserCredential>.value(
              _FakeUserCredential_6(
                this,
                Invocation.method(#reauthenticateWithCredential, [credential]),
              ),
            ),
          )
          as _i4.Future<_i7.UserCredential>);

  @override
  _i4.Future<void> reload() =>
      (super.noSuchMethod(
            Invocation.method(#reload, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> sendEmailVerification([
    _i6.ActionCodeSettings? actionCodeSettings,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#sendEmailVerification, [actionCodeSettings]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i7.User> unlink(String? providerId) =>
      (super.noSuchMethod(
            Invocation.method(#unlink, [providerId]),
            returnValue: _i4.Future<_i7.User>.value(
              _FakeUser_12(this, Invocation.method(#unlink, [providerId])),
            ),
          )
          as _i4.Future<_i7.User>);

  @override
  _i4.Future<void> updatePassword(String? newPassword) =>
      (super.noSuchMethod(
            Invocation.method(#updatePassword, [newPassword]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updatePhoneNumber(
    _i6.PhoneAuthCredential? phoneCredential,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePhoneNumber, [phoneCredential]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateDisplayName(String? displayName) =>
      (super.noSuchMethod(
            Invocation.method(#updateDisplayName, [displayName]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updatePhotoURL(String? photoURL) =>
      (super.noSuchMethod(
            Invocation.method(#updatePhotoURL, [photoURL]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateProfile({String? displayName, String? photoURL}) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #displayName: displayName,
              #photoURL: photoURL,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> verifyBeforeUpdateEmail(
    String? newEmail, [
    _i6.ActionCodeSettings? actionCodeSettings,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#verifyBeforeUpdateEmail, [
              newEmail,
              actionCodeSettings,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [FirebaseStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseStorage extends _i1.Mock implements _i8.FirebaseStorage {
  MockFirebaseStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.FirebaseApp get app =>
      (super.noSuchMethod(
            Invocation.getter(#app),
            returnValue: _FakeFirebaseApp_4(this, Invocation.getter(#app)),
          )
          as _i5.FirebaseApp);

  @override
  String get bucket =>
      (super.noSuchMethod(
            Invocation.getter(#bucket),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.getter(#bucket),
            ),
          )
          as String);

  @override
  Duration get maxOperationRetryTime =>
      (super.noSuchMethod(
            Invocation.getter(#maxOperationRetryTime),
            returnValue: _FakeDuration_13(
              this,
              Invocation.getter(#maxOperationRetryTime),
            ),
          )
          as Duration);

  @override
  Duration get maxUploadRetryTime =>
      (super.noSuchMethod(
            Invocation.getter(#maxUploadRetryTime),
            returnValue: _FakeDuration_13(
              this,
              Invocation.getter(#maxUploadRetryTime),
            ),
          )
          as Duration);

  @override
  Duration get maxDownloadRetryTime =>
      (super.noSuchMethod(
            Invocation.getter(#maxDownloadRetryTime),
            returnValue: _FakeDuration_13(
              this,
              Invocation.getter(#maxDownloadRetryTime),
            ),
          )
          as Duration);

  @override
  set app(_i5.FirebaseApp? value) => super.noSuchMethod(
    Invocation.setter(#app, value),
    returnValueForMissingStub: null,
  );

  @override
  set bucket(String? value) => super.noSuchMethod(
    Invocation.setter(#bucket, value),
    returnValueForMissingStub: null,
  );

  @override
  Map<dynamic, dynamic> get pluginConstants =>
      (super.noSuchMethod(
            Invocation.getter(#pluginConstants),
            returnValue: <dynamic, dynamic>{},
          )
          as Map<dynamic, dynamic>);

  @override
  _i8.Reference ref([String? path]) =>
      (super.noSuchMethod(
            Invocation.method(#ref, [path]),
            returnValue: _FakeReference_14(
              this,
              Invocation.method(#ref, [path]),
            ),
          )
          as _i8.Reference);

  @override
  _i8.Reference refFromURL(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#refFromURL, [url]),
            returnValue: _FakeReference_14(
              this,
              Invocation.method(#refFromURL, [url]),
            ),
          )
          as _i8.Reference);

  @override
  void setMaxOperationRetryTime(Duration? time) => super.noSuchMethod(
    Invocation.method(#setMaxOperationRetryTime, [time]),
    returnValueForMissingStub: null,
  );

  @override
  void setMaxUploadRetryTime(Duration? time) => super.noSuchMethod(
    Invocation.method(#setMaxUploadRetryTime, [time]),
    returnValueForMissingStub: null,
  );

  @override
  void setMaxDownloadRetryTime(Duration? time) => super.noSuchMethod(
    Invocation.method(#setMaxDownloadRetryTime, [time]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> useStorageEmulator(
    String? host,
    int? port, {
    bool? automaticHostMapping = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #useStorageEmulator,
              [host, port],
              {#automaticHostMapping: automaticHostMapping},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [Reference].
///
/// See the documentation for Mockito's code generation for more information.
class MockReference extends _i1.Mock implements _i8.Reference {
  MockReference() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.FirebaseStorage get storage =>
      (super.noSuchMethod(
            Invocation.getter(#storage),
            returnValue: _FakeFirebaseStorage_15(
              this,
              Invocation.getter(#storage),
            ),
          )
          as _i8.FirebaseStorage);

  @override
  String get bucket =>
      (super.noSuchMethod(
            Invocation.getter(#bucket),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.getter(#bucket),
            ),
          )
          as String);

  @override
  String get fullPath =>
      (super.noSuchMethod(
            Invocation.getter(#fullPath),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.getter(#fullPath),
            ),
          )
          as String);

  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.getter(#name),
            ),
          )
          as String);

  @override
  _i8.Reference get root =>
      (super.noSuchMethod(
            Invocation.getter(#root),
            returnValue: _FakeReference_14(this, Invocation.getter(#root)),
          )
          as _i8.Reference);

  @override
  _i8.Reference child(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#child, [path]),
            returnValue: _FakeReference_14(
              this,
              Invocation.method(#child, [path]),
            ),
          )
          as _i8.Reference);

  @override
  _i4.Future<void> delete() =>
      (super.noSuchMethod(
            Invocation.method(#delete, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String> getDownloadURL() =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadURL, []),
            returnValue: _i4.Future<String>.value(
              _i13.dummyValue<String>(
                this,
                Invocation.method(#getDownloadURL, []),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<_i9.FullMetadata> getMetadata() =>
      (super.noSuchMethod(
            Invocation.method(#getMetadata, []),
            returnValue: _i4.Future<_i9.FullMetadata>.value(
              _FakeFullMetadata_16(this, Invocation.method(#getMetadata, [])),
            ),
          )
          as _i4.Future<_i9.FullMetadata>);

  @override
  _i4.Future<_i8.ListResult> list([_i9.ListOptions? options]) =>
      (super.noSuchMethod(
            Invocation.method(#list, [options]),
            returnValue: _i4.Future<_i8.ListResult>.value(
              _FakeListResult_17(this, Invocation.method(#list, [options])),
            ),
          )
          as _i4.Future<_i8.ListResult>);

  @override
  _i4.Future<_i8.ListResult> listAll() =>
      (super.noSuchMethod(
            Invocation.method(#listAll, []),
            returnValue: _i4.Future<_i8.ListResult>.value(
              _FakeListResult_17(this, Invocation.method(#listAll, [])),
            ),
          )
          as _i4.Future<_i8.ListResult>);

  @override
  _i4.Future<_i15.Uint8List?> getData([int? maxSize = 10485760]) =>
      (super.noSuchMethod(
            Invocation.method(#getData, [maxSize]),
            returnValue: _i4.Future<_i15.Uint8List?>.value(),
          )
          as _i4.Future<_i15.Uint8List?>);

  @override
  _i8.UploadTask putData(
    _i15.Uint8List? data, [
    _i9.SettableMetadata? metadata,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#putData, [data, metadata]),
            returnValue: _FakeUploadTask_18(
              this,
              Invocation.method(#putData, [data, metadata]),
            ),
          )
          as _i8.UploadTask);

  @override
  _i8.UploadTask putBlob(dynamic blob, [_i9.SettableMetadata? metadata]) =>
      (super.noSuchMethod(
            Invocation.method(#putBlob, [blob, metadata]),
            returnValue: _FakeUploadTask_18(
              this,
              Invocation.method(#putBlob, [blob, metadata]),
            ),
          )
          as _i8.UploadTask);

  @override
  _i8.UploadTask putFile(_i16.File? file, [_i9.SettableMetadata? metadata]) =>
      (super.noSuchMethod(
            Invocation.method(#putFile, [file, metadata]),
            returnValue: _FakeUploadTask_18(
              this,
              Invocation.method(#putFile, [file, metadata]),
            ),
          )
          as _i8.UploadTask);

  @override
  _i8.UploadTask putString(
    String? data, {
    _i9.PutStringFormat? format = _i9.PutStringFormat.raw,
    _i9.SettableMetadata? metadata,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #putString,
              [data],
              {#format: format, #metadata: metadata},
            ),
            returnValue: _FakeUploadTask_18(
              this,
              Invocation.method(
                #putString,
                [data],
                {#format: format, #metadata: metadata},
              ),
            ),
          )
          as _i8.UploadTask);

  @override
  _i4.Future<_i9.FullMetadata> updateMetadata(_i9.SettableMetadata? metadata) =>
      (super.noSuchMethod(
            Invocation.method(#updateMetadata, [metadata]),
            returnValue: _i4.Future<_i9.FullMetadata>.value(
              _FakeFullMetadata_16(
                this,
                Invocation.method(#updateMetadata, [metadata]),
              ),
            ),
          )
          as _i4.Future<_i9.FullMetadata>);

  @override
  _i8.DownloadTask writeToFile(_i16.File? file) =>
      (super.noSuchMethod(
            Invocation.method(#writeToFile, [file]),
            returnValue: _FakeDownloadTask_19(
              this,
              Invocation.method(#writeToFile, [file]),
            ),
          )
          as _i8.DownloadTask);
}

/// A class which mocks [UploadTask].
///
/// See the documentation for Mockito's code generation for more information.
class MockUploadTask extends _i1.Mock implements _i8.UploadTask {
  MockUploadTask() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.FirebaseStorage get storage =>
      (super.noSuchMethod(
            Invocation.getter(#storage),
            returnValue: _FakeFirebaseStorage_15(
              this,
              Invocation.getter(#storage),
            ),
          )
          as _i8.FirebaseStorage);

  @override
  _i4.Stream<_i8.TaskSnapshot> get snapshotEvents =>
      (super.noSuchMethod(
            Invocation.getter(#snapshotEvents),
            returnValue: _i4.Stream<_i8.TaskSnapshot>.empty(),
          )
          as _i4.Stream<_i8.TaskSnapshot>);

  @override
  _i8.TaskSnapshot get snapshot =>
      (super.noSuchMethod(
            Invocation.getter(#snapshot),
            returnValue: _FakeTaskSnapshot_20(
              this,
              Invocation.getter(#snapshot),
            ),
          )
          as _i8.TaskSnapshot);

  @override
  _i4.Future<bool> pause() =>
      (super.noSuchMethod(
            Invocation.method(#pause, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> resume() =>
      (super.noSuchMethod(
            Invocation.method(#resume, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> cancel() =>
      (super.noSuchMethod(
            Invocation.method(#cancel, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Stream<_i8.TaskSnapshot> asStream() =>
      (super.noSuchMethod(
            Invocation.method(#asStream, []),
            returnValue: _i4.Stream<_i8.TaskSnapshot>.empty(),
          )
          as _i4.Stream<_i8.TaskSnapshot>);

  @override
  _i4.Future<_i8.TaskSnapshot> catchError(
    Function? onError, {
    bool Function(Object)? test,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#catchError, [onError], {#test: test}),
            returnValue: _i4.Future<_i8.TaskSnapshot>.value(
              _FakeTaskSnapshot_20(
                this,
                Invocation.method(#catchError, [onError], {#test: test}),
              ),
            ),
          )
          as _i4.Future<_i8.TaskSnapshot>);

  @override
  _i4.Future<S> then<S>(
    _i4.FutureOr<S> Function(_i8.TaskSnapshot)? onValue, {
    Function? onError,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#then, [onValue], {#onError: onError}),
            returnValue:
                _i13.ifNotNull(
                  _i13.dummyValueOrNull<S>(
                    this,
                    Invocation.method(#then, [onValue], {#onError: onError}),
                  ),
                  (S v) => _i4.Future<S>.value(v),
                ) ??
                _FakeFuture_3<S>(
                  this,
                  Invocation.method(#then, [onValue], {#onError: onError}),
                ),
          )
          as _i4.Future<S>);

  @override
  _i4.Future<_i8.TaskSnapshot> whenComplete(
    _i4.FutureOr<dynamic> Function()? action,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#whenComplete, [action]),
            returnValue: _i4.Future<_i8.TaskSnapshot>.value(
              _FakeTaskSnapshot_20(
                this,
                Invocation.method(#whenComplete, [action]),
              ),
            ),
          )
          as _i4.Future<_i8.TaskSnapshot>);

  @override
  _i4.Future<_i8.TaskSnapshot> timeout(
    Duration? timeLimit, {
    _i4.FutureOr<_i8.TaskSnapshot> Function()? onTimeout,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#timeout, [timeLimit], {#onTimeout: onTimeout}),
            returnValue: _i4.Future<_i8.TaskSnapshot>.value(
              _FakeTaskSnapshot_20(
                this,
                Invocation.method(
                  #timeout,
                  [timeLimit],
                  {#onTimeout: onTimeout},
                ),
              ),
            ),
          )
          as _i4.Future<_i8.TaskSnapshot>);
}

/// A class which mocks [TaskSnapshot].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskSnapshot extends _i1.Mock implements _i8.TaskSnapshot {
  MockTaskSnapshot() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.FirebaseStorage get storage =>
      (super.noSuchMethod(
            Invocation.getter(#storage),
            returnValue: _FakeFirebaseStorage_15(
              this,
              Invocation.getter(#storage),
            ),
          )
          as _i8.FirebaseStorage);

  @override
  int get bytesTransferred =>
      (super.noSuchMethod(Invocation.getter(#bytesTransferred), returnValue: 0)
          as int);

  @override
  _i8.Reference get ref =>
      (super.noSuchMethod(
            Invocation.getter(#ref),
            returnValue: _FakeReference_14(this, Invocation.getter(#ref)),
          )
          as _i8.Reference);

  @override
  _i9.TaskState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i9.TaskState.paused,
          )
          as _i9.TaskState);

  @override
  int get totalBytes =>
      (super.noSuchMethod(Invocation.getter(#totalBytes), returnValue: 0)
          as int);
}
