// Mocks generated by Mockito 5.4.6 from annotations
// in greenhive_app/test/services/message_send_handler_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter/src/animation/curves.dart' as _i9;
import 'package:flutter/widgets.dart' as _i8;
import 'package:greenhive_app/data/models/models.dart' as _i2;
import 'package:greenhive_app/data/repositories/chat/chat_message_repository.dart'
    as _i4;
import 'package:greenhive_app/data/repositories/interfaces/repository_interfaces.dart'
    as _i6;
import 'package:greenhive_app/shared/services/profanity/profanity_filter_service.dart'
    as _i10;
import 'package:greenhive_app/shared/services/profanity/profanity_models.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:scrollable_positioned_list/scrollable_positioned_list.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMessage_0 extends _i1.SmartFake implements _i2.Message {
  _FakeMessage_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProfanityConfig_1 extends _i1.SmartFake
    implements _i3.ProfanityConfig {
  _FakeProfanityConfig_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProfanityResult_2 extends _i1.SmartFake
    implements _i3.ProfanityResult {
  _FakeProfanityResult_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ChatMessageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatMessageRepository extends _i1.Mock
    implements _i4.ChatMessageRepository {
  @override
  _i5.Stream<List<_i2.Message>> getMessagesStream(
    String? roomId, {
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMessagesStream, [roomId], {#limit: limit}),
            returnValue: _i5.Stream<List<_i2.Message>>.empty(),
            returnValueForMissingStub: _i5.Stream<List<_i2.Message>>.empty(),
          )
          as _i5.Stream<List<_i2.Message>>);

  @override
  _i5.Future<(List<_i2.Message>, _i6.PaginationCursor?)>
  getLastMessagesWithCursor(String? roomId, {int? limit = 50}) =>
      (super.noSuchMethod(
            Invocation.method(
              #getLastMessagesWithCursor,
              [roomId],
              {#limit: limit},
            ),
            returnValue:
                _i5.Future<(List<_i2.Message>, _i6.PaginationCursor?)>.value((
                  <_i2.Message>[],
                  null,
                )),
            returnValueForMissingStub:
                _i5.Future<(List<_i2.Message>, _i6.PaginationCursor?)>.value((
                  <_i2.Message>[],
                  null,
                )),
          )
          as _i5.Future<(List<_i2.Message>, _i6.PaginationCursor?)>);

  @override
  _i5.Future<(List<_i2.Message>, _i6.PaginationCursor?)> loadOlderMessages(
    String? roomId, {
    required _i6.PaginationCursor? cursor,
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #loadOlderMessages,
              [roomId],
              {#cursor: cursor, #limit: limit},
            ),
            returnValue:
                _i5.Future<(List<_i2.Message>, _i6.PaginationCursor?)>.value((
                  <_i2.Message>[],
                  null,
                )),
            returnValueForMissingStub:
                _i5.Future<(List<_i2.Message>, _i6.PaginationCursor?)>.value((
                  <_i2.Message>[],
                  null,
                )),
          )
          as _i5.Future<(List<_i2.Message>, _i6.PaginationCursor?)>);

  @override
  _i5.Future<_i2.Message> sendMessage(String? roomId, _i2.Message? message) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [roomId, message]),
            returnValue: _i5.Future<_i2.Message>.value(
              _FakeMessage_0(
                this,
                Invocation.method(#sendMessage, [roomId, message]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.Message>.value(
              _FakeMessage_0(
                this,
                Invocation.method(#sendMessage, [roomId, message]),
              ),
            ),
          )
          as _i5.Future<_i2.Message>);

  @override
  _i5.Future<void> sendCallLogMessage({
    required String? roomId,
    required String? senderId,
    required String? callerId,
    required bool? isVideo,
    required int? durationSeconds,
    required String? status,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendCallLogMessage, [], {
              #roomId: roomId,
              #senderId: senderId,
              #callerId: callerId,
              #isVideo: isVideo,
              #durationSeconds: durationSeconds,
              #status: status,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateMessage(
    String? roomId,
    String? messageId,
    String? newText,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateMessage, [roomId, messageId, newText]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteMessage(String? roomId, String? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMessage, [roomId, messageId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteMessages(String? roomId, List<String>? messageIds) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMessages, [roomId, messageIds]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [ItemScrollController].
///
/// See the documentation for Mockito's code generation for more information.
class MockItemScrollController extends _i1.Mock
    implements _i7.ItemScrollController {
  @override
  bool get isAttached =>
      (super.noSuchMethod(
            Invocation.getter(#isAttached),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void jumpTo({required int? index, double? alignment = 0.0}) =>
      super.noSuchMethod(
        Invocation.method(#jumpTo, [], {#index: index, #alignment: alignment}),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> scrollTo({
    required int? index,
    double? alignment = 0.0,
    required Duration? duration,
    _i8.Curve? curve = _i9.Curves.linear,
    List<double>? opacityAnimationWeights = const [40.0, 20.0, 40.0],
  }) =>
      (super.noSuchMethod(
            Invocation.method(#scrollTo, [], {
              #index: index,
              #alignment: alignment,
              #duration: duration,
              #curve: curve,
              #opacityAnimationWeights: opacityAnimationWeights,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [ProfanityFilterService].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfanityFilterService extends _i1.Mock
    implements _i10.ProfanityFilterService {
  @override
  _i3.ProfanityConfig get config =>
      (super.noSuchMethod(
            Invocation.getter(#config),
            returnValue: _FakeProfanityConfig_1(
              this,
              Invocation.getter(#config),
            ),
            returnValueForMissingStub: _FakeProfanityConfig_1(
              this,
              Invocation.getter(#config),
            ),
          )
          as _i3.ProfanityConfig);

  @override
  bool get isInitialized =>
      (super.noSuchMethod(
            Invocation.getter(#isInitialized),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i5.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i3.ProfanityResult> checkProfanity(
    String? text, {
    String? language,
    String? context,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #checkProfanity,
              [text],
              {#language: language, #context: context},
            ),
            returnValue: _i5.Future<_i3.ProfanityResult>.value(
              _FakeProfanityResult_2(
                this,
                Invocation.method(
                  #checkProfanity,
                  [text],
                  {#language: language, #context: context},
                ),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i3.ProfanityResult>.value(
              _FakeProfanityResult_2(
                this,
                Invocation.method(
                  #checkProfanity,
                  [text],
                  {#language: language, #context: context},
                ),
              ),
            ),
          )
          as _i5.Future<_i3.ProfanityResult>);

  @override
  _i5.Future<_i3.ProfanityResult> checkProfanitySubstring(
    String? text, {
    String? language,
    String? context,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #checkProfanitySubstring,
              [text],
              {#language: language, #context: context},
            ),
            returnValue: _i5.Future<_i3.ProfanityResult>.value(
              _FakeProfanityResult_2(
                this,
                Invocation.method(
                  #checkProfanitySubstring,
                  [text],
                  {#language: language, #context: context},
                ),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i3.ProfanityResult>.value(
              _FakeProfanityResult_2(
                this,
                Invocation.method(
                  #checkProfanitySubstring,
                  [text],
                  {#language: language, #context: context},
                ),
              ),
            ),
          )
          as _i5.Future<_i3.ProfanityResult>);

  @override
  _i3.ProfanityResult checkProfanitySync(
    String? text, {
    String? language,
    String? context,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #checkProfanitySync,
              [text],
              {#language: language, #context: context},
            ),
            returnValue: _FakeProfanityResult_2(
              this,
              Invocation.method(
                #checkProfanitySync,
                [text],
                {#language: language, #context: context},
              ),
            ),
            returnValueForMissingStub: _FakeProfanityResult_2(
              this,
              Invocation.method(
                #checkProfanitySync,
                [text],
                {#language: language, #context: context},
              ),
            ),
          )
          as _i3.ProfanityResult);

  @override
  _i5.Future<void> refreshConfig() =>
      (super.noSuchMethod(
            Invocation.method(#refreshConfig, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void addCustomWords(String? language, Set<String>? words) =>
      super.noSuchMethod(
        Invocation.method(#addCustomWords, [language, words]),
        returnValueForMissingStub: null,
      );

  @override
  void removeCustomWords(String? language, Set<String>? words) =>
      super.noSuchMethod(
        Invocation.method(#removeCustomWords, [language, words]),
        returnValueForMissingStub: null,
      );
}
