// Mocks generated by Mockito 5.4.6 from annotations
// in securityexperts_app/test/features/home/home_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:securityexperts_app/core/logging/app_logger.dart' as _i7;
import 'package:securityexperts_app/data/models/models.dart' as _i6;
import 'package:securityexperts_app/features/chat/services/unread_messages_service.dart'
    as _i3;
import 'package:securityexperts_app/features/home/services/home_data_loader.dart'
    as _i4;
import 'package:securityexperts_app/utils/expert_search_utils.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeExpertSearchUtils_0 extends _i1.SmartFake
    implements _i2.ExpertSearchUtils {
  _FakeExpertSearchUtils_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUnreadMessagesService_1 extends _i1.SmartFake
    implements _i3.UnreadMessagesService {
  _FakeUnreadMessagesService_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HomeDataLoader].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeDataLoader extends _i1.Mock implements _i4.HomeDataLoader {
  MockHomeDataLoader() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ExpertSearchUtils get searchUtils =>
      (super.noSuchMethod(
            Invocation.getter(#searchUtils),
            returnValue: _FakeExpertSearchUtils_0(
              this,
              Invocation.getter(#searchUtils),
            ),
          )
          as _i2.ExpertSearchUtils);

  @override
  _i3.UnreadMessagesService get unreadMessagesService =>
      (super.noSuchMethod(
            Invocation.getter(#unreadMessagesService),
            returnValue: _FakeUnreadMessagesService_1(
              this,
              Invocation.getter(#unreadMessagesService),
            ),
          )
          as _i3.UnreadMessagesService);

  @override
  _i5.Future<void> initializeData({
    required dynamic Function()? onExpertsLoaded,
    required dynamic Function()? onError,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#initializeData, [], {
              #onExpertsLoaded: onExpertsLoaded,
              #onError: onError,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i6.User>?> loadExperts() =>
      (super.noSuchMethod(
            Invocation.method(#loadExperts, []),
            returnValue: _i5.Future<List<_i6.User>?>.value(),
          )
          as _i5.Future<List<_i6.User>?>);

  @override
  _i5.Future<List<_i6.Product>?> loadProducts() =>
      (super.noSuchMethod(
            Invocation.method(#loadProducts, []),
            returnValue: _i5.Future<List<_i6.Product>?>.value(),
          )
          as _i5.Future<List<_i6.Product>?>);
}

/// A class which mocks [UnreadMessagesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUnreadMessagesService extends _i1.Mock
    implements _i3.UnreadMessagesService {
  MockUnreadMessagesService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<int> getTotalUnreadCount() =>
      (super.noSuchMethod(
            Invocation.method(#getTotalUnreadCount, []),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> getRoomUnreadCount(String? roomId) =>
      (super.noSuchMethod(
            Invocation.method(#getRoomUnreadCount, [roomId]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<void> recalculateTotalUnreadCount() =>
      (super.noSuchMethod(
            Invocation.method(#recalculateTotalUnreadCount, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Stream<int> getTotalUnreadCountStream() =>
      (super.noSuchMethod(
            Invocation.method(#getTotalUnreadCountStream, []),
            returnValue: _i5.Stream<int>.empty(),
          )
          as _i5.Stream<int>);

  @override
  _i5.Stream<int> getRoomUnreadCountStream(String? roomId) =>
      (super.noSuchMethod(
            Invocation.method(#getRoomUnreadCountStream, [roomId]),
            returnValue: _i5.Stream<int>.empty(),
          )
          as _i5.Stream<int>);

  @override
  _i5.Future<void> markRoomAsRead(String? roomId) =>
      (super.noSuchMethod(
            Invocation.method(#markRoomAsRead, [roomId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> markRoomsAsRead(List<String>? roomIds) =>
      (super.noSuchMethod(
            Invocation.method(#markRoomsAsRead, [roomIds]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getRoomsWithUnreadMessages() =>
      (super.noSuchMethod(
            Invocation.method(#getRoomsWithUnreadMessages, []),
            returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i5.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [AppLogger].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppLogger extends _i1.Mock implements _i7.AppLogger {
  MockAppLogger() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void verbose(String? message, {String? tag, Map<String, dynamic>? data}) =>
      super.noSuchMethod(
        Invocation.method(#verbose, [message], {#tag: tag, #data: data}),
        returnValueForMissingStub: null,
      );

  @override
  void debug(String? message, {String? tag, Map<String, dynamic>? data}) =>
      super.noSuchMethod(
        Invocation.method(#debug, [message], {#tag: tag, #data: data}),
        returnValueForMissingStub: null,
      );

  @override
  void info(String? message, {String? tag, Map<String, dynamic>? data}) =>
      super.noSuchMethod(
        Invocation.method(#info, [message], {#tag: tag, #data: data}),
        returnValueForMissingStub: null,
      );

  @override
  void warning(String? message, {String? tag, Map<String, dynamic>? data}) =>
      super.noSuchMethod(
        Invocation.method(#warning, [message], {#tag: tag, #data: data}),
        returnValueForMissingStub: null,
      );

  @override
  void error(
    String? message, {
    String? tag,
    dynamic error,
    StackTrace? stackTrace,
    Map<String, dynamic>? data,
  }) => super.noSuchMethod(
    Invocation.method(
      #error,
      [message],
      {#tag: tag, #error: error, #stackTrace: stackTrace, #data: data},
    ),
    returnValueForMissingStub: null,
  );
}
