// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNcNVnt6Td9FJ_0aOLcLSU-t4DLdYFlHk',
    appId: '1:1015827376061:web:03f59d7cd8330245ca54d4',
    messagingSenderId: '1015827376061',
    projectId: 'securityexp-app',
    authDomain: 'securityexp-app.firebaseapp.com',
    databaseURL: 'https://securityexp-app-default-rtdb.firebaseio.com',
    storageBucket: 'securityexp-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe9D55nX2YJq1aIMf6uPW4gFNokaffbVo',
    appId: '1:1015827376061:android:30b282d2d31bcaadca54d4',
    messagingSenderId: '1015827376061',
    projectId: 'securityexp-app',
    databaseURL: 'https://securityexp-app-default-rtdb.firebaseio.com',
    storageBucket: 'securityexp-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbp_cYNPSnPOlYMnTtnGKJUCbwOSbtvbM',
    appId: '1:1015827376061:ios:23864d39adb5e70cca54d4',
    messagingSenderId: '1015827376061',
    projectId: 'securityexp-app',
    databaseURL: 'https://securityexp-app-default-rtdb.firebaseio.com',
    storageBucket: 'securityexp-app.firebasestorage.app',
    iosBundleId: 'com.example.securityexpertsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbp_cYNPSnPOlYMnTtnGKJUCbwOSbtvbM',
    appId: '1:1015827376061:ios:23864d39adb5e70cca54d4',
    messagingSenderId: '1015827376061',
    projectId: 'securityexp-app',
    databaseURL: 'https://securityexp-app-default-rtdb.firebaseio.com',
    storageBucket: 'securityexp-app.firebasestorage.app',
    iosBundleId: 'com.example.securityexpertsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNcNVnt6Td9FJ_0aOLcLSU-t4DLdYFlHk',
    appId: '1:1015827376061:web:0f03cd329136db44ca54d4',
    messagingSenderId: '1015827376061',
    projectId: 'securityexp-app',
    authDomain: 'securityexp-app.firebaseapp.com',
    databaseURL: 'https://securityexp-app-default-rtdb.firebaseio.com',
    storageBucket: 'securityexp-app.firebasestorage.app',
  );

}