// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFJU1ZSrkTScFxefLApd5aZPQ9hhuyVwE',
    appId: '1:1054913877112:web:f0ad4e836010646a12898d',
    messagingSenderId: '1054913877112',
    projectId: 'greenhive-service',
    authDomain: 'greenhive-service.firebaseapp.com',
    databaseURL: 'https://greenhive-service-default-rtdb.firebaseio.com',
    storageBucket: 'greenhive-service.firebasestorage.app',
    measurementId: 'G-MXN7VL3EYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWJxZLhNVUTPN84l6jyjSPY9urMkuCa0Q',
    appId: '1:1054913877112:android:84654b1b4e0249a112898d',
    messagingSenderId: '1054913877112',
    projectId: 'greenhive-service',
    storageBucket: 'greenhive-service.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGO8k0rMKrLe6OHSZSTvivK9aa_0ozTjo',
    appId: '1:1054913877112:ios:076f7d8ba3ca91f912898d',
    messagingSenderId: '1054913877112',
    projectId: 'greenhive-service',
    storageBucket: 'greenhive-service.firebasestorage.app',
    iosClientId:
        '1054913877112-gkai1rogp8b68u26n29bonuon0na8869.apps.googleusercontent.com',
    iosBundleId: 'com.example.securityexpertsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGO8k0rMKrLe6OHSZSTvivK9aa_0ozTjo',
    appId: '1:1054913877112:ios:076f7d8ba3ca91f912898d',
    messagingSenderId: '1054913877112',
    projectId: 'greenhive-service',
    storageBucket: 'greenhive-service.firebasestorage.app',
    iosClientId:
        '1054913877112-gkai1rogp8b68u26n29bonuon0na8869.apps.googleusercontent.com',
    iosBundleId: 'com.example.securityexpertsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFJU1ZSrkTScFxefLApd5aZPQ9hhuyVwE',
    appId: '1:1054913877112:web:1169f51b96a19da312898d',
    messagingSenderId: '1054913877112',
    projectId: 'greenhive-service',
    authDomain: 'greenhive-service.firebaseapp.com',
    storageBucket: 'greenhive-service.firebasestorage.app',
    measurementId: 'G-GGTPCD51N5',
  );
}
