// Mocks generated by Mockito 5.4.6 from annotations
// in securityexperts_app/test/features/support/new_ticket_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cloud_firestore/cloud_firestore.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:securityexperts_app/core/logging/app_logger.dart' as _i7;
import 'package:securityexperts_app/features/support/data/models/models.dart'
    as _i5;
import 'package:securityexperts_app/features/support/services/support_analytics.dart'
    as _i8;
import 'package:securityexperts_app/features/support/services/support_models.dart'
    as _i2;
import 'package:securityexperts_app/features/support/services/support_service.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSupportResult_0<T> extends _i1.SmartFake
    implements _i2.SupportResult<T> {
  _FakeSupportResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SupportService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupportService extends _i1.Mock implements _i3.SupportService {
  MockSupportService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.SupportResult<_i5.SupportTicket>> createTicket({
    required _i5.TicketType? type,
    required _i5.TicketCategory? category,
    required String? subject,
    required String? description,
    List<_i5.PendingAttachment>? attachments,
    String? userEmail,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createTicket, [], {
              #type: type,
              #category: category,
              #subject: subject,
              #description: description,
              #attachments: attachments,
              #userEmail: userEmail,
            }),
            returnValue: _i4.Future<_i2.SupportResult<_i5.SupportTicket>>.value(
              _FakeSupportResult_0<_i5.SupportTicket>(
                this,
                Invocation.method(#createTicket, [], {
                  #type: type,
                  #category: category,
                  #subject: subject,
                  #description: description,
                  #attachments: attachments,
                  #userEmail: userEmail,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.SupportResult<_i5.SupportTicket>>);

  @override
  _i4.Future<_i2.SupportResult<List<_i5.SupportTicket>>> getUserTickets({
    _i5.TicketStatus? statusFilter,
    _i5.TicketType? typeFilter,
    int? limit = 20,
    _i6.DocumentSnapshot<Object?>? startAfter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUserTickets, [], {
              #statusFilter: statusFilter,
              #typeFilter: typeFilter,
              #limit: limit,
              #startAfter: startAfter,
            }),
            returnValue:
                _i4.Future<_i2.SupportResult<List<_i5.SupportTicket>>>.value(
                  _FakeSupportResult_0<List<_i5.SupportTicket>>(
                    this,
                    Invocation.method(#getUserTickets, [], {
                      #statusFilter: statusFilter,
                      #typeFilter: typeFilter,
                      #limit: limit,
                      #startAfter: startAfter,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.SupportResult<List<_i5.SupportTicket>>>);

  @override
  _i4.Future<_i2.SupportResult<List<_i5.SupportTicket>>> getOpenTickets() =>
      (super.noSuchMethod(
            Invocation.method(#getOpenTickets, []),
            returnValue:
                _i4.Future<_i2.SupportResult<List<_i5.SupportTicket>>>.value(
                  _FakeSupportResult_0<List<_i5.SupportTicket>>(
                    this,
                    Invocation.method(#getOpenTickets, []),
                  ),
                ),
          )
          as _i4.Future<_i2.SupportResult<List<_i5.SupportTicket>>>);

  @override
  _i4.Future<_i2.SupportResult<_i5.SupportTicket>> getTicketById(
    String? ticketId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTicketById, [ticketId]),
            returnValue: _i4.Future<_i2.SupportResult<_i5.SupportTicket>>.value(
              _FakeSupportResult_0<_i5.SupportTicket>(
                this,
                Invocation.method(#getTicketById, [ticketId]),
              ),
            ),
          )
          as _i4.Future<_i2.SupportResult<_i5.SupportTicket>>);

  @override
  _i4.Stream<_i5.SupportTicket?> watchTicket(String? ticketId) =>
      (super.noSuchMethod(
            Invocation.method(#watchTicket, [ticketId]),
            returnValue: _i4.Stream<_i5.SupportTicket?>.empty(),
          )
          as _i4.Stream<_i5.SupportTicket?>);

  @override
  _i4.Stream<List<_i5.SupportTicket>> watchUserTickets({
    _i5.TicketStatus? statusFilter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watchUserTickets, [], {
              #statusFilter: statusFilter,
            }),
            returnValue: _i4.Stream<List<_i5.SupportTicket>>.empty(),
          )
          as _i4.Stream<List<_i5.SupportTicket>>);

  @override
  _i4.Future<int> getUnreadTicketCount() =>
      (super.noSuchMethod(
            Invocation.method(#getUnreadTicketCount, []),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<_i5.SupportMessage>> getTicketMessages(String? ticketId) =>
      (super.noSuchMethod(
            Invocation.method(#getTicketMessages, [ticketId]),
            returnValue: _i4.Future<List<_i5.SupportMessage>>.value(
              <_i5.SupportMessage>[],
            ),
          )
          as _i4.Future<List<_i5.SupportMessage>>);

  @override
  _i4.Stream<List<_i5.SupportMessage>> watchTicketMessages(String? ticketId) =>
      (super.noSuchMethod(
            Invocation.method(#watchTicketMessages, [ticketId]),
            returnValue: _i4.Stream<List<_i5.SupportMessage>>.empty(),
          )
          as _i4.Stream<List<_i5.SupportMessage>>);

  @override
  _i4.Future<_i2.SupportResult<_i5.SupportMessage>> replyToTicket({
    required String? ticketId,
    required String? content,
    List<_i5.PendingAttachment>? attachments,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#replyToTicket, [], {
              #ticketId: ticketId,
              #content: content,
              #attachments: attachments,
            }),
            returnValue:
                _i4.Future<_i2.SupportResult<_i5.SupportMessage>>.value(
                  _FakeSupportResult_0<_i5.SupportMessage>(
                    this,
                    Invocation.method(#replyToTicket, [], {
                      #ticketId: ticketId,
                      #content: content,
                      #attachments: attachments,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.SupportResult<_i5.SupportMessage>>);

  @override
  _i4.Future<void> markMessagesAsRead(String? ticketId) =>
      (super.noSuchMethod(
            Invocation.method(#markMessagesAsRead, [ticketId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.SupportResult<void>> rateSupportExperience({
    required String? ticketId,
    required int? rating,
    String? comment,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#rateSupportExperience, [], {
              #ticketId: ticketId,
              #rating: rating,
              #comment: comment,
            }),
            returnValue: _i4.Future<_i2.SupportResult<void>>.value(
              _FakeSupportResult_0<void>(
                this,
                Invocation.method(#rateSupportExperience, [], {
                  #ticketId: ticketId,
                  #rating: rating,
                  #comment: comment,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.SupportResult<void>>);
}

/// A class which mocks [AppLogger].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppLogger extends _i1.Mock implements _i7.AppLogger {
  MockAppLogger() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void verbose(String? message, {String? tag, Map<String, dynamic>? data}) =>
      super.noSuchMethod(
        Invocation.method(#verbose, [message], {#tag: tag, #data: data}),
        returnValueForMissingStub: null,
      );

  @override
  void debug(String? message, {String? tag, Map<String, dynamic>? data}) =>
      super.noSuchMethod(
        Invocation.method(#debug, [message], {#tag: tag, #data: data}),
        returnValueForMissingStub: null,
      );

  @override
  void info(String? message, {String? tag, Map<String, dynamic>? data}) =>
      super.noSuchMethod(
        Invocation.method(#info, [message], {#tag: tag, #data: data}),
        returnValueForMissingStub: null,
      );

  @override
  void warning(String? message, {String? tag, Map<String, dynamic>? data}) =>
      super.noSuchMethod(
        Invocation.method(#warning, [message], {#tag: tag, #data: data}),
        returnValueForMissingStub: null,
      );

  @override
  void error(
    String? message, {
    String? tag,
    dynamic error,
    StackTrace? stackTrace,
    Map<String, dynamic>? data,
  }) => super.noSuchMethod(
    Invocation.method(
      #error,
      [message],
      {#tag: tag, #error: error, #stackTrace: stackTrace, #data: data},
    ),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [SupportAnalytics].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupportAnalytics extends _i1.Mock implements _i8.SupportAnalytics {
  MockSupportAnalytics() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> trackHubOpened() =>
      (super.noSuchMethod(
            Invocation.method(#trackHubOpened, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> trackTicketStarted({required _i5.TicketType? type}) =>
      (super.noSuchMethod(
            Invocation.method(#trackTicketStarted, [], {#type: type}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> trackTicketSubmitted({
    required String? ticketId,
    required _i5.TicketType? type,
    required _i5.TicketCategory? category,
    required _i5.TicketPriority? priority,
    required int? attachmentCount,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackTicketSubmitted, [], {
              #ticketId: ticketId,
              #type: type,
              #category: category,
              #priority: priority,
              #attachmentCount: attachmentCount,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> trackTicketViewed({
    required String? ticketId,
    required _i5.TicketStatus? status,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackTicketViewed, [], {
              #ticketId: ticketId,
              #status: status,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> trackMessageSent({
    required String? ticketId,
    required int? attachmentCount,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackMessageSent, [], {
              #ticketId: ticketId,
              #attachmentCount: attachmentCount,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> trackSatisfactionRated({
    required String? ticketId,
    required int? rating,
    required bool? hasComment,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackSatisfactionRated, [], {
              #ticketId: ticketId,
              #rating: rating,
              #hasComment: hasComment,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> trackAttachmentAdded({
    required String? ticketId,
    required String? mimeType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackAttachmentAdded, [], {
              #ticketId: ticketId,
              #mimeType: mimeType,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> trackTicketFiltered({
    required _i5.TicketStatus? statusFilter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackTicketFiltered, [], {
              #statusFilter: statusFilter,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
