package com.goaegent.securityexperts

import android.content.Context
import android.util.Log
import com.google.firebase.FirebaseApp
import com.google.firebase.FirebaseOptions

/**
 * Ensures a usable default [FirebaseApp] exists in the current process.
 *
 * Why this exists:
 *   Cold-start processes spawned by FCM (e.g. our broadcast-receiver
 *   triggered foreground service / inline reject thread / WorkManager
 *   worker) sometimes execute BEFORE `FirebaseInitProvider`
 *   (the ContentProvider that normally auto-initializes the default
 *   FirebaseApp via google-services.json). When that happens
 *   `FirebaseAuth.getInstance()` throws:
 *
 *     IllegalStateException: Default FirebaseApp is not initialized
 *     in this process com.goaegent.securityexperts. Make sure to call
 *     FirebaseApp.initializeApp(Context) first.
 *
 *   A naive `FirebaseApp.initializeApp(context)` may silently return
 *   null if the auto-init pathway is in a half-initialized state, so
 *   we fall back to explicit [FirebaseOptions] read from the same
 *   string resources the google-services plugin generates from
 *   google-services.json. This is the same data FirebaseInitProvider
 *   would have used; we just inject it ourselves.
 */
internal object FirebaseBootstrap {
    private const val TAG = "FirebaseBootstrap"

    @Volatile
    private var ready: Boolean = false

    /**
     * Idempotent. Safe to call from any thread, any process state.
     * Returns true if a default FirebaseApp is available by the time
     * the call returns.
     */
    fun ensureInitialized(context: Context): Boolean {
        if (ready) return true
        return synchronized(this) {
            if (ready) return@synchronized true
            val app = context.applicationContext
            Log.i(TAG, "ensureInitialized: starting, pid=${android.os.Process.myPid()} pkg=${app.packageName}")

            // 1. Fast path — if FirebaseInitProvider already ran, this returns.
            try {
                FirebaseApp.getInstance()
                ready = true
                Log.i(TAG, "ensureInitialized: tier-1 OK (FirebaseApp.getInstance succeeded)")
                return@synchronized true
            } catch (e: IllegalStateException) {
                Log.i(TAG, "ensureInitialized: tier-1 miss (${e.message}) — trying tier-2")
            }

            // 2. Standard path — read options from string resources.
            try {
                val initialized = FirebaseApp.initializeApp(app)
                if (initialized != null) {
                    ready = true
                    Log.i(TAG, "ensureInitialized: tier-2 OK (FirebaseApp.initializeApp returned non-null)")
                    return@synchronized true
                }
                Log.w(TAG, "ensureInitialized: tier-2 returned null — trying tier-3 (manual options)")
            } catch (t: Throwable) {
                Log.w(TAG, "ensureInitialized: tier-2 threw — trying tier-3", t)
            }

            // 3. Manual path — read each value from string resources and
            //    construct FirebaseOptions ourselves. These resources are
            //    generated by the com.google.gms.google-services plugin
            //    from google-services.json at build time.
            val opts: FirebaseOptions? = try {
                buildOptionsFromResources(app)
            } catch (t: Throwable) {
                Log.e(TAG, "ensureInitialized: tier-3 buildOptionsFromResources threw", t)
                null
            }
            if (opts == null) {
                Log.e(
                    TAG,
                    "ensureInitialized: tier-3 FAILED — google_app_id resource missing. " +
                        "Check that com.google.gms.google-services plugin is applied " +
                        "and that google-services.json is present at app/google-services.json.",
                )
                return@synchronized false
            }
            Log.i(TAG, "ensureInitialized: tier-3 built FirebaseOptions appId=${opts.applicationId} projectId=${opts.projectId}")
            try {
                FirebaseApp.initializeApp(app, opts)
                ready = true
                Log.i(TAG, "ensureInitialized: tier-3 OK (manual FirebaseOptions accepted)")
                true
            } catch (t: Throwable) {
                Log.e(TAG, "ensureInitialized: tier-3 FirebaseApp.initializeApp(app, opts) threw", t)
                // It's possible another thread won the race and initialized it
                // between our checks. Try once more.
                try {
                    FirebaseApp.getInstance()
                    ready = true
                    Log.i(TAG, "ensureInitialized: tier-3 recovered via getInstance after race")
                    true
                } catch (_: IllegalStateException) {
                    false
                }
            }
        }
    }

    private fun buildOptionsFromResources(context: Context): FirebaseOptions? {
        val appId = stringRes(context, "google_app_id") ?: return null
        val builder = FirebaseOptions.Builder().setApplicationId(appId)
        stringRes(context, "google_api_key")?.let { builder.setApiKey(it) }
        stringRes(context, "gcm_defaultSenderId")?.let { builder.setGcmSenderId(it) }
        stringRes(context, "firebase_database_url")?.let { builder.setDatabaseUrl(it) }
        stringRes(context, "google_storage_bucket")?.let { builder.setStorageBucket(it) }
        stringRes(context, "project_id")?.let { builder.setProjectId(it) }
        return builder.build()
    }

    private fun stringRes(context: Context, name: String): String? {
        val id = context.resources.getIdentifier(name, "string", context.packageName)
        if (id == 0) return null
        val value = context.getString(id)
        return if (value.isBlank()) null else value
    }
}
