import 'package:flutter/material.dart';
import 'package:securityexperts_app/features/admin/services/admin_skills_service.dart';
import 'package:securityexperts_app/shared/themes/app_colors.dart';
import 'package:securityexperts_app/shared/themes/app_typography.dart';

/// List item widget for displaying a skill category in admin views.
class SkillCategoryListItem extends StatelessWidget {
  final SkillCategory category;
  final int skillCount;

  const SkillCategoryListItem({
    super.key,
    required this.category,
    required this.skillCount,
  });

  @override
  Widget build(BuildContext context) {
    return Card(
      color: AppColors.surface,
      margin: const EdgeInsets.only(bottom: 8),
      child: ListTile(
        leading: _CategoryAvatar(category: category),
        title: Text(
          category.name,
          style: AppTypography.bodyRegular.copyWith(
            color: AppColors.textPrimary,
          ),
        ),
        subtitle: Text(
          '$skillCount ${skillCount == 1 ? 'skill' : 'skills'}',
          style: AppTypography.bodySmall.copyWith(
            color: AppColors.textSecondary,
          ),
        ),
        trailing: const _AutoGeneratedBadge(),
      ),
    );
  }
}

class _CategoryAvatar extends StatelessWidget {
  final SkillCategory category;

  const _CategoryAvatar({required this.category});

  @override
  Widget build(BuildContext context) {
    return CircleAvatar(
      backgroundColor: AppColors.primary.withValues(alpha: 0.1),
      child: Text(
        category.icon ?? '🛠️',
        style: const TextStyle(fontSize: 20),
      ),
    );
  }
}

class _AutoGeneratedBadge extends StatelessWidget {
  const _AutoGeneratedBadge();

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
      decoration: BoxDecoration(
        color: AppColors.primaryLight.withValues(alpha: 0.1),
        borderRadius: BorderRadius.circular(4),
      ),
      child: Text(
        'Auto-generated',
        style: AppTypography.bodySmall.copyWith(
          color: AppColors.primaryLight,
          fontSize: 10,
        ),
      ),
    );
  }
}

/// Info banner for categories tab explaining auto-generation.
class CategoryInfoBanner extends StatelessWidget {
  const CategoryInfoBanner({super.key});

  @override
  Widget build(BuildContext context) {
    return Container(
      margin: const EdgeInsets.all(16),
      padding: const EdgeInsets.all(12),
      decoration: BoxDecoration(
        color: AppColors.primary.withValues(alpha: 0.1),
        borderRadius: BorderRadius.circular(8),
        border: Border.all(
          color: AppColors.primary.withValues(alpha: 0.3),
        ),
      ),
      child: Row(
        children: [
          const Icon(
            Icons.info_outline,
            color: AppColors.primary,
            size: 20,
          ),
          const SizedBox(width: 12),
          Expanded(
            child: Text(
              'Categories are automatically created from skills. Add skills with new categories to create them.',
              style: AppTypography.bodySmall.copyWith(
                color: AppColors.primary,
              ),
            ),
          ),
        ],
      ),
    );
  }
}

/// Empty state widget for categories list.
class CategoryEmptyState extends StatelessWidget {
  const CategoryEmptyState({super.key});

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          const Icon(
            Icons.category_outlined,
            size: 64,
            color: AppColors.textSecondary,
          ),
          const SizedBox(height: 16),
          Text(
            'No categories yet',
            style: AppTypography.bodyRegular.copyWith(
              color: AppColors.textSecondary,
            ),
          ),
          const SizedBox(height: 8),
          Text(
            'Create skills to generate categories',
            style: AppTypography.bodySmall.copyWith(
              color: AppColors.textSecondary,
            ),
          ),
        ],
      ),
    );
  }
}
