// Mocks generated by Mockito 5.4.6 from annotations
// in securityexperts_app/test/features/ratings/rating_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:securityexperts_app/core/logging/app_logger.dart' as _i5;
import 'package:securityexperts_app/features/ratings/data/models/rating.dart'
    as _i4;
import 'package:securityexperts_app/features/ratings/services/rating_service.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRatingResult_0<T> extends _i1.SmartFake
    implements _i2.RatingResult<T> {
  _FakeRatingResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RatingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRatingService extends _i1.Mock implements _i2.RatingService {
  MockRatingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.RatingResult<_i4.Rating>> submitRating({
    required String? expertId,
    required String? expertName,
    required String? bookingId,
    required int? stars,
    String? comment,
    bool? isAnonymous = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#submitRating, [], {
              #expertId: expertId,
              #expertName: expertName,
              #bookingId: bookingId,
              #stars: stars,
              #comment: comment,
              #isAnonymous: isAnonymous,
            }),
            returnValue: _i3.Future<_i2.RatingResult<_i4.Rating>>.value(
              _FakeRatingResult_0<_i4.Rating>(
                this,
                Invocation.method(#submitRating, [], {
                  #expertId: expertId,
                  #expertName: expertName,
                  #bookingId: bookingId,
                  #stars: stars,
                  #comment: comment,
                  #isAnonymous: isAnonymous,
                }),
              ),
            ),
          )
          as _i3.Future<_i2.RatingResult<_i4.Rating>>);

  @override
  _i3.Future<List<_i4.Rating>> getExpertRatings({
    required String? expertId,
    int? limit = 20,
    _i4.Rating? lastRating,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getExpertRatings, [], {
              #expertId: expertId,
              #limit: limit,
              #lastRating: lastRating,
            }),
            returnValue: _i3.Future<List<_i4.Rating>>.value(<_i4.Rating>[]),
          )
          as _i3.Future<List<_i4.Rating>>);

  @override
  _i3.Future<List<_i4.Rating>> getMyRatings() =>
      (super.noSuchMethod(
            Invocation.method(#getMyRatings, []),
            returnValue: _i3.Future<List<_i4.Rating>>.value(<_i4.Rating>[]),
          )
          as _i3.Future<List<_i4.Rating>>);

  @override
  _i3.Future<bool> hasRatedBooking(String? bookingId) =>
      (super.noSuchMethod(
            Invocation.method(#hasRatedBooking, [bookingId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<_i4.Rating?> getRatingForBooking(String? bookingId) =>
      (super.noSuchMethod(
            Invocation.method(#getRatingForBooking, [bookingId]),
            returnValue: _i3.Future<_i4.Rating?>.value(),
          )
          as _i3.Future<_i4.Rating?>);

  @override
  _i3.Future<Map<String, dynamic>> getExpertRatingStats(String? expertId) =>
      (super.noSuchMethod(
            Invocation.method(#getExpertRatingStats, [expertId]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Stream<List<_i4.Rating>> watchExpertRatings(
    String? expertId, {
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watchExpertRatings, [expertId], {#limit: limit}),
            returnValue: _i3.Stream<List<_i4.Rating>>.empty(),
          )
          as _i3.Stream<List<_i4.Rating>>);
}

/// A class which mocks [AppLogger].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppLogger extends _i1.Mock implements _i5.AppLogger {
  MockAppLogger() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void verbose(String? message, {String? tag, Map<String, dynamic>? data}) =>
      super.noSuchMethod(
        Invocation.method(#verbose, [message], {#tag: tag, #data: data}),
        returnValueForMissingStub: null,
      );

  @override
  void debug(String? message, {String? tag, Map<String, dynamic>? data}) =>
      super.noSuchMethod(
        Invocation.method(#debug, [message], {#tag: tag, #data: data}),
        returnValueForMissingStub: null,
      );

  @override
  void info(String? message, {String? tag, Map<String, dynamic>? data}) =>
      super.noSuchMethod(
        Invocation.method(#info, [message], {#tag: tag, #data: data}),
        returnValueForMissingStub: null,
      );

  @override
  void warning(String? message, {String? tag, Map<String, dynamic>? data}) =>
      super.noSuchMethod(
        Invocation.method(#warning, [message], {#tag: tag, #data: data}),
        returnValueForMissingStub: null,
      );

  @override
  void error(
    String? message, {
    String? tag,
    dynamic error,
    StackTrace? stackTrace,
    Map<String, dynamic>? data,
  }) => super.noSuchMethod(
    Invocation.method(
      #error,
      [message],
      {#tag: tag, #error: error, #stackTrace: stackTrace, #data: data},
    ),
    returnValueForMissingStub: null,
  );
}
